### ISSUE TITLE
LAKES add wbic codes to database

### ISSUE THREAD

**Issue by joneslabND** [MFEh2o/db#10]
Maybe they are in there? If not, we can add them

**Comment by ross-alex** [comment]
WBICs are already there. However, the following lakeIDs are missing WBICs

Lake of the Hills (LH) - WBIC: 1620500
Lost Lake (LT) - WBIC: 1593400 (also, lats and longs are missing -- 45.97, -89.48)

**Comment by katiesaunders** [comment]
I added these WBIC codes. I also searched for the other WI lakes without them using this website: https://dnr.wi.gov/lakes/documents/LakeMaps.aspx, but they were not listed.
