### ISSUE TITLE
FISH_INFO Duplicate tag numbers on different fish

### ISSUE THREAD

**Issue by kaijagahm** [MFEh2o/db#104]
Check for any duplicate tag numbers on different fish 
Note: I wonder if the `tagID` column, which I've recently removed, was originally created to make it easy to search through tags on fish (i.e. you could group_by(tagID) and then see if you had different fishNum's). Wonder if we should put `tagID` back.

The obvious problem, though, is that fish could have more than one tag, or they could have an applied tag vs. a recaptured tag.

_Originally posted by @kaijagahm in https://github.com/MFEh2o/db/issues/22#issuecomment-742758612_

**Comment by kaijagahm** [comment]
Reproducing here our Slack thread from 18 December 2020, for documentation purposes.

@Randinotte:
Hi @cdassow, @kaijagahm found a new issue with Camp data in FISH_INFO from 2018 where all of the pit tag numbers were cut off (down to only 7 digits), which makes all the fish have the same tagRecaputre and tagApply ("900.228006"). We wanted to retrace the steps from datasheet to database entry, but can't find any raw csv data from the Camp Lake experiment, either the digitized datasheets or the compiled fish entry tool output. Can you think back and remember if you sent that to Alex? Also, do you have any of those files personally that we could evaluate?

Noting here- a connected issue is that many fish have tagRecaptureType "pit" with no tag number ("NA"). [KG note: resolved in #22.]

@cdassow:
Ya that was before the fish entry tool was created, I remember wrestling (it really made me dislike excel for a while haha) with this during the analysis, I'll see if I can dig up the old sheets. I'm on an online writing retreat with Chelsey all day today but planning to work tomorrow so I'll take a look at this then maybe.

The tagRecaptureType pits with no tag numbers are likely fish that we recapped and knew were pitted but they escaped before we could scan them. For that experiment we used larger pit tags and implanted them with a scalpel so it was obvious which fish had tags since they had little scars from the implant. [KG note: resolved in #22.]

**Comment by kaijagahm** [comment]
Next steps: Colin will check his files to see if he has the excel sheets from these samples.

**Comment by cdassow** [comment]
Here you go, I guess I can't attach .csv files here but if you prefer that I have one I can send
[20181115_fishScapes_survey_hyperstability_2018.xlsx](https://github.com/MFEh2o/db/files/5719601/20181115_fishScapes_survey_hyperstability_2018.xlsx)

**Comment by kaijagahm** [comment]
@cdassow thanks for uploading this. xlsx is fine--I just converted to csv. 

I'm noticing that a bunch of fish in this document have the metadataID hyperstability.20180604. That metadataID doesn't show up at all in FISH_INFO or FISH_SAMPLES, it's not in METADATA, and I can't find any documents that reference it on Box. Seems like maybe just an incorrect date that we can safely change to hyperstability.20180521? But there are 6 sampleID's in the document you sent that have that metadataID, so I want to get to the bottom of it.

**Comment by cdassow** [comment]
1. Ya that metadataID is wrong and the other ones are too, I think it's an artifact of the old way we entered data using that .xlsx file and dragging down to fillout columns, occasionally people (myself included) would forget to hold ctrl down so that it would automatically count up numbers on the metadataID column. I've also checked over the 0521 metadata on Box and it's complete and accurate.
2. Yup the fish numbers are likely wrong. Could have Randi spot check a few since the binder is in SB. Those are probably all my fault. The undergrads often pointed out that when numbering data sheets in the field I'd skip or duplicate fish numbers sometimes, doesn't really matter what the fishnumber is as long as it's not duplicated. We wouldn't have double pitted any fish.

**Comment by kaijagahm** [comment]
Thank you, that's very helpful!

**Comment by kaijagahm** [comment]
So, we have duplicate pit tag numbers (in the pitApply column, so it's not an apply/recapture issue) in almost all years, but they appear most frequently in the 2018 data, which is what Colin attached above.

I have only looked at 2018 so far.
Overview:
1. The data from Colin is saved in .xlsx format. The only way to get the pit tag numbers to show up in full, as far as I can tell, is to format all the cells in the spreadsheet as "text". But after converting to csv, the "text" format goes away, and those extra digits get lost.
2. One possible way to fix (1) would be to use openxlsx or a similar package to read the data in directly from excel to R. That would fix the digits issue.
3. But more broadly, I'm worried about this because it's a very easy thing to overlook. What if, in a year from now, we forget that we need to read the data through excel instead of through a csv, and then we run into this exact same problem again?
4. A bunch of fishID's in Colin's doc above have more than one associated tag number. This does NOT seem to be a case of putting more than one tag on the same fish; instead, it's a case of accidentally-duplicated fishID's/fishNums. Based on preliminary investigations, Alex or whoever entered these data went through and re-assigned fishID's to get rid of the duplicates. That's good. But it also creates a problem for me because I need to somehow map the full pit tag numbers to the correct fish, and I don't have a record of how these changes were made. Did Alex leave a trail? I haven't checked yet.

Here's a complete map of the 2018 data

First, I took the 2018 FISH_INFO from Colin (above) and filtered it down to only fish that had tagApplyType == "pit" and !is.na(tagApply). Put in terms of the new columns, I filtered it down to fish for which !is.na(pitApply). Pulled out just sampleID, fishID, and pitApply (renamed). Called that 'patch' and prepared to apply it to FISH_INFO as a patch to fix the pit tag numbers for those fishID's. 

patch:
867 rows, 832 unique fishID's, 56 unique sampleID's

Before applying the patch, I did some checks. 

**Split 1: duplicate vs. single fishID's**
1a: duplicate fishID's
- 65 rows, representing 30 unique fishID's.
- Same fishID's with different tag numbers
- 5 fishID's have 3 unique tag numbers each; the rest (25 unique fishID's) have 2 tag numbers each.
- All of these fishID's do show up in FISH_INFO (database).

Colin confirms that these are *not* the same fish with multiple tags applied. Instead, they'd be accidental repeat fishID's. To confirm this, I checked measurements (e.g. fishLength, gpsWaypoint), and they were different.

I looked up some of the fish by their species, fishLength, and gpsWaypoint in the database (FISH_INFO). They seem to be present, but with different fish numbers. So in order to match these up properly, I will need to know which changes Alex (or someone) made to the fish numbers/ID's (as described in part 4 of the overview above).

1b: unique fishID's
- 802 rows (fish)

**Split 2: Out of unique fishID's: in database vs. not**
2a: unique fishID's that are not in FISH_INFO (database)
- 78 rows (fish)

**Split 3: out of the unique fishID's that don't appear in FISH_INFO (database), is the *sampleID* in the database?**
3a. sampleID not in the database
- 76 rows (fish)
- 6 sampleID's
- All of these have the metadataID "hyperstability.20180604", and all do show up in the database if that metadataID is changed to "hyperstability.20180521". Confirmed with Colin that this is the correct change to make. Have yet to do this.

3b. sampleID is in the database
- 2 fishID's. Note that other fish for this sampleID are present, just not this fishID.
- Searched by fish weight and gpsWaypoint: turns out these fish *are* in the database, just under a different fishID. So they're accounted for. Just need to change the fishID's for these fish in 'patch' before making the patch.

2b: unique fishID's that are in FISH_INFO (database)
- 724 rows. These are all set.

**Comment by kaijagahm** [comment]
Fixed the ID's described in the previous comment, which should have taken care of all of the 2018 duplicate pitApply numbers. But it didn't. The ones left fall into three categories.


Next steps after this:
1. Look into other years besides 2018
2. Check pitRecapture for duplicate numbers (but be careful, because these could be legit)
2. Check floyApply for duplicate numbers
3. Check floyRecapture for duplicate numbers (but be careful, because these could be legit)
4. (maybe?) check that there aren't numbers in the recapture columns that don't appear in the apply columns? Or maybe not, if it's possible tags were applied but never recorded.

**Comment by kaijagahm** [comment]
@Randinotte here's a list of the data sheets that I need checked, whenever you can get to it. What I'm interested in for these are the pit tag numbers: all of these should have a pit tag that was applied, as opposed to being recorded as a recap (though of course let me know if that's not the case).

It might be easier for you to just take photos of the data sheets, since there are rather a lot of these. That'll work fine.

*Hyperstability 2018 (listed in date order--all are CS WholeShoreline)*
**CS**
CS_WholeShoreline_20180528_1830_AN_hyperstability.20180521_2
CS_WholeShoreline_20180531_0120_BE_hyperstability.20180521_23
CS_WholeShoreline_20180625_1245_AN_hyperstability.20180521_1 (any chance the tag number is actually 622 instead of 672?)
CS_WholeShoreline_20180626_0150_BE_hyperstability.20180521
CS_WholeShoreline_20180709_2035_AN_hyperstability.20180521_7
CS_WholeShoreline_20180711_2310_BE_hyperstability.20180521

*MarkRecap 2018 (listed in date order within each lake, fish from the same sampleID grouped together)*
**WL**
WL_WholeShoreline_20180508_2325_BE_MarkRecap.20120228_23
WL_WholeShoreline_20180508_2325_BE_MarkRecap.20120228_63

WL_WholeShoreline_20180511_2140_BE_MarkRecap.20120228_8

WL_WholeShoreline_20180604_0925_AN_MarkRecap.20120228_13

WL_WholeShoreline_20180730_0920_AN_MarkRecap.20120228_38

WL_WholeShoreline_20180928_0110_BE_MarkRecap.20120228_3

**FE**
EL_WholeShoreline_20180510_2315_BE_MarkRecap.20120228_37

EL_WholeShoreline_20180511_2340_BE_MarkRecap.20120228_17

FE_WholeShoreline_20180929_1540_AN_MarkRecap.20120228_1
FE_WholeShoreline_20180929_1540_AN_MarkRecap.20120228_2

**Comment by kaijagahm** [comment]
I decided to peek ahead and see about the state of duplicate tag numbers in years other than 2018. Note that I have not yet taken a look at pitRecapture, floyApply, or floyRecapture. Just moving forward with pitApply duplicates in non-2018 years.

Note that there may be some singleton rows in here; that's because some of the duplicates span years (i.e. one fish is in 2017, another in 2018) and here I've just excluded all 2018 samples. 
[dupPitApply_non2018.txt](https://github.com/MFEh2o/db/files/5752061/dupPitApply_non2018.txt)

Next step is to chat with @Randinotte and make a game plan.

**Comment by Randinotte** [comment]
@kaijagahm Here's the list of duplicate fishIDs that I checked today. A few were typos, some were written even on the datasheets as duplicates, and one case (highlighted in green) is particularly strange. There are a few notes at the bottom of the spreadsheet. "Photo" number in the spreadsheet corresponds to the page number in the group's PDF. Note that the CS photos are out of chronological order. 

[duplicateFishIDs_GH104.xlsx](https://github.com/MFEh2o/db/files/5765849/duplicateFishIDs_GH104.xlsx)
[WL fish datasheets 2018.pdf](https://github.com/MFEh2o/db/files/5765879/WL.fish.datasheets.2018.pdf)
[CS fish datasheets 2018.pdf](https://github.com/MFEh2o/db/files/5765880/CS.fish.datasheets.2018.pdf)
[FE fish datasheets 2018.pdf](https://github.com/MFEh2o/db/files/5765881/FE.fish.datasheets.2018.pdf)

**Comment by kaijagahm** [comment]
Thanks, @Randinotte!
Also, I'm giggling at how you pre-emptively included a column for my comments. You know me so well...

**Comment by kaijagahm** [comment]
Randi and I ran into a really thorny issue with two tag numbers today. The numbers are 900F67000093081 and 900F67000093018.

Each of these numbers appear twice in the database. Here's a photo that summarizes the situation: 
![weirdFishProblem](https://user-images.githubusercontent.com/37053323/103581011-2c9f2980-4ea9-11eb-96fd-d38422b15174.jpg)

Clearly, there are several errors here.
1. It doesn't make sense for tag 18 to start out as a recap (this is the first time it comes up in the database). After consulting with @ctsolomon, I've gone ahead and changed this to pitApply.
2. The way the tags are currently, both fish switch species from LMB to YWP.
3. The measurements don't stack up, at least for tag 81 (since it was caught just two hours apart). It's also weird that this fish was caught first in WL and then in EL on the same night. Maybe could have crossed the curtain or been accidentally released on the wrong side, but that seems pretty unlikely.
4. Note that the measurements for tag 18 could conceivably be true--that would be a fair bit of growth for a fish from September to May, but it's definitely not out of the question. 
5. It's fairly easy to mix up apply vs. recapture on data sheets. Harder to mix up ID's.
6. We've verified this information against paper data sheets. None of the tag numbers look like they were mistranscribed from paper to digital data sheets. Would be easy to explain this if some of them were e.g. 13 instead of 18, but they all appear to legitimately be 18 and 81. 
7. It's suspicious that on 5/11/2018 in WL, the fish with tag 18 and the fish with tag 81 are next to each other on the data sheet. But even though swapping the tag numbers would fix the species-switching problem, it would make the measurements even more absurdly incorrect, so I don't think this is the answer.

For now, we have elected no make no further changes beyond changing the 2017 fish from pitRecapture to pitApply. We've made a comment in each row to indicate that there's a problem and that these data shouldn't be used for analysis.

**Comment by kaijagahm** [comment]
Broadly, the game plan here is:
1. Check for, and correct, any further duplicates in 2018 except for the unresolvable ones described above.
2. Look into duplicates in the floyApply column
3. Get started on pitApply and floyApply from another year.
4. Rinse and repeat.
5. After *Apply columns are dealt with, think about how to comb through the recapture columns.

**Comment by kaijagahm** [comment]
Okay, these are basically all going to need to have data sheets checked.

@Randinotte here are text files containing repeat pit and floy tags
[moreDupTagIDsFloy.txt](https://github.com/MFEh2o/db/files/5837125/moreDupTagIDsFloy.txt)
[moreDupTagIDsPit.txt](https://github.com/MFEh2o/db/files/5837126/moreDupTagIDsPit.txt)

**Comment by Randinotte** [comment]
Here is the first spreadsheet of checked fish tag numbers. The tags in red (4 pairs of duplicates) are those where both duplicates are clearly written as that exact tag number and both as pitApply. I therefore assume that the second instance would be moved to tagRecap. The green pair is the set with a sticky note, still waiting to hear back from Amaryllis in case she knows what it means. 

[moreDupTagIDsPit.xlsx](https://github.com/MFEh2o/db/files/5857941/moreDupTagIDsPit.xlsx)

**Comment by kaijagahm** [comment]
This is great, thanks @Randinotte! I'm glad to see that most of these were at least somewhat resolvable.

**Comment by kaijagahm** [comment]
Finished resolving these pit tag numbers. Need to still do floys, after Randi has gotten back to me with the checked datasheets. Double-checked to make sure all the pit tag numbers actually got resolved.

**Comment by kaijagahm** [comment]
Resolved floys. Double checked that both pits and floys are resolved. Am not going to check the recap columns because it will be too hard to know if they're right or not: e.g. duplicates are expected. We'd end up checking everything manually.

**Comment by cdassow** [comment]
This sounds great @kaijagahm! One thing you could consider if you have the time is looking at the extreme recaps, I agree checking all of them isn't feasible unless we want to sink a lot of time into going through paper data sheets. Extreme cases that might be identified with a bit of coding would be fish that are recapped really far apart or really close in time.  A threshold for what's 'really far apart' would be the maximum life span of the fish. For LMBs which are pretty much all we've tagged, we'd expect fish to max out at about 20 years of age (the oldest recorded LMB anywhere is 23yrs). On the other end of the spectrum, a threshold for what we'd consider 'too short' of a time between recaps is <24 hrs. We'd expect few bass to be recaptured within the same day (especially for angling recaptures).

**Comment by kaijagahm** [comment]
Thanks, Colin: I'm going to make your suggestion into a new issue so as to avoid going down a rabbit hole with this one. 

This issue as it stands is ready for db update.

**Comment by kaijagahm** [comment]
Updated as part of 4.4.0
