### ISSUE TITLE
missing updateID's in FISH_SAMPLES and UNITS

### ISSUE THREAD

**Issue by kaijagahm** [MFEh2o/db#113]
From an email I sent Randi on 12/28/2020:

> In preparing the fish tables for another database update, I noticed that there are a bunch of missing updateID's in FISH_SAMPLES. I dug back through old scripts, and it looks like the culprit is a rogue case_when() statement in your writingUpdatingDBtables_20201207.R script: you forgot to add the TRUE ~ clause, so all of the updateID's beyond the ones you were assigning got set to NA.
> 
> This happens to me all. the. time. (I really don't know why the function is written this way--seems like it should default to keeping the rest of the column the way it is! I might write a version that does that, one of these days). Anyway. Totally understandable mistake.
> 
> I found the line in the script where the error occurred, and I thought I could fix it by just copying that part of your code into my script, but on second look I think I'm going to need to go over it with you.
> 
> When you see this, let's find a time to hop on a call and figure out how best to address this problem. Should be fairly straightforward once we can take a look together. Hooray for reproducible code!

**Comment by kaijagahm** [comment]
@Randinotte and I are going to go over this in a meeting right after the checkin tomorrow morning (1/5).

Randi also discovered a similar error in the UNITS table. This was almost certainly introduced by me in one of my meta scripts. Ugh.

I'm starting to think I should write a version of case_when where the default behavior is not to fill everything with NA.

**Comment by Randinotte** [comment]
Pushed db update 4.2.1 "(Hydro)xychloroquine" today, which resolved updateID errors in FISH_SAMPLES and UNITS. I don't think I can close the issue, but @kaijagahm can.
