### ISSUE TITLE
GC - NA in dateTimeSample causes issues

### ISSUE THREAD

**Issue by joneslabND** [MFEh2o/db#131]
Appears that there are ~190 NA values for dateTimeSample in 2019 (maybe 2020 too?). These caused dbTable() to fail because as.POSIXct() choked on NA values. I updated the as.POSIXct() call in dbTable() with the optional=TRUE argument to avoid the error from not returning the table from the database. Unfortunately, with optional=TRUE it doesn't handle the NA's on a case-by-case basis, but rather makes all fo the dateTimeSample values <NA>... 

Not sure if we need to fix the NA values in the database or more carefully fix handling NA values in dateTimeSample in the dbTable function.

**Comment by kaijagahm** [comment]
Yeah, I had noticed this. I need to work on the GC table in a major way pretty soon anyway, tied in with #99. Will keep this in mind.

**Comment by kaijagahm** [comment]
Fixed with version 4.5.1, which isn't on Box yet.
