### ISSUE TITLE
limnoEntryTool notes

### ISSUE THREAD

**Issue by kaijagahm** [MFEh2o/db#140]
We'll use this for brainstorming fixes/additions for the limno entry tool. @Randinotte put your suggestion about off-limits projectID's here.

**Comment by Randinotte** [comment]
Seems like the tool is switching date formats for dateSample and dateTimeSample. This at least occurred in the output file profilesIS.csv for 2019 and 2020.

**Comment by Randinotte** [comment]
Idea for off-limits projectIDs- If there are projectIDs that are "retired" it wouldn't be hard to make the entry tool reject them. For example, 1-12, 14, 16, 18-33, 39-40. ProjectID mix-ups don't happen frequently but I've found a few.

**Comment by Randinotte** [comment]
@kaijagahm Here's the log files correction script that I used at the end of the season. Looking though it, it only addresses a siteName/sampleID issue. Apparently whenever the depthClass == "surface" it made the siteName == "PML". As we said on the call today, it's probably an issue where a column number is hard-coded. 

```
#Log files from 2020 have "PML" instead of the correct siteName (Inlet1, Inlet2, Inlet3, Outlet) in their sampleID's 
  #whenever the siteName=="Surface". PML, Hypo, and point are ok.

#Script corrects log files and writes new csv's to a folder called "correctedFiles"
library(tidyverse)

wrong<- "logFiles2020/originalFiles"
right<- "logFiles2020/correctedFiles"
files<-list.files(wrong)
files<-files[grep('.csv',files)]

#checking which log files have this problem: 
samples<- read.csv("logFiles2020/originalFiles/samplesIS.csv", header = T, stringsAsFactors = F) #was ok originally
profiles<- read.csv("logFiles2020/originalFiles/profilesIS.csv", header = T, stringsAsFactors = F) #does not have inlet/outlet
#also no inlet/outlet samples: bp, chl, or zoop

i=2
r=32

for (i in c(3:6,9)){
  orig<- read.csv(file.path(wrong,files[i])) #read in log file
  new<- orig %>% 
    mutate(sampleID = as.character(sampleID)) %>% 
    mutate(sampleID = case_when(site == "Inlet1" ~ gsub("PML", "Inlet1", orig$sampleID), 
                                site == "Inlet2" ~ gsub("PML", "Inlet2", orig$sampleID),
                                site == "Inlet3" ~ gsub("PML", "Inlet3", orig$sampleID),
                                site == "Outlet" ~ gsub("PML", "Outlet", orig$sampleID),
                                TRUE ~ sampleID))
  write.csv(new, file.path(right, files[i]), row.names = F)
}

#checking output: (all good)
newColor<- read.csv("logFiles2020/correctedFiles/colorLogFile.csv", header = T, stringsAsFactors = F)
newDOC<- read.csv("logFiles2020/correctedFiles/docLogFile.csv", header = T, stringsAsFactors = F)
newfiltered<- read.csv("logFiles2020/correctedFiles/filteredLogFile.csv", header = T, stringsAsFactors = F)
newunfiltered<- read.csv("logFiles2020/correctedFiles/unfilteredLogFile.csv", header = T, stringsAsFactors = F)
newpoc<- read.csv("logFiles2020/correctedFiles/pocLogFile.csv", header = T, stringsAsFactors = F)

#moving unaffected log files over to the correctedFiles folder: 
move<-files[c(1:2, 7:8, 10)]
i=1
for (i in 1:length(move)){
  file.copy(file.path("logFiles2020/originalFiles",move[i],sep=""),file.path("logFiles2020/correctedFiles",move[i],sep=""))
}
```

**Comment by kaijagahm** [comment]
From meeting with Randi 4/26:
- Does limno entry tool compare e.g. pH values (etc) to past data from db? (Need to know for testing). Yes--it pulls LAKES, LIMNO_PROFILES, and SAMPLES data from the db version. We'll have to set it to an earlier db version to test it on new data.
- Space in id number randomly--sometimes, but not other times?
- When inlet1--assigning PML in place of siteName (inlet1). So it comes out inlet1_Surface. Not good!

**Comment by Randinotte** [comment]
Clarifying the last bullet issue- the error occurs whenever the depthClass is "Surface", which makes this occur whenever the siteName is Inlet1, Inlet2, Inlet3, or Outlet. This makes the sampleID say, for example, "ME_**PML**_20200610_0936_Surface_0_Limno.Sample.20160505" (incorrect) instead of "ME_**Outlet**_20200610_0936_Surface_0_Limno.Sample.20160505" (correct).

**Comment by Randinotte** [comment]
A helpful check based on a current snag- sampleID's generated by the entry tool didn't include a preceeding 0 for 3-digit times (resulted in _932_ instead of _0932_). Not sure if this got fixed for the 2020 Limno Entry Tool or if I coded the fix later.

**Comment by kaijagahm** [comment]
> @kaijagahm Here's the log files correction script that I used at the end of the season. Looking though it, it only addresses a siteName/sampleID issue. Apparently whenever the depthClass == "surface" it made the siteName == "PML". As we said on the call today, it's probably an issue where a column number is hard-coded.
> 
> ```
> #Log files from 2020 have "PML" instead of the correct siteName (Inlet1, Inlet2, Inlet3, Outlet) in their sampleID's 
>   #whenever the siteName=="Surface". PML, Hypo, and point are ok.
> 
> #Script corrects log files and writes new csv's to a folder called "correctedFiles"
> library(tidyverse)
> 
> wrong<- "logFiles2020/originalFiles"
> right<- "logFiles2020/correctedFiles"
> files<-list.files(wrong)
> files<-files[grep('.csv',files)]
> 
> #checking which log files have this problem: 
> samples<- read.csv("logFiles2020/originalFiles/samplesIS.csv", header = T, stringsAsFactors = F) #was ok originally
> profiles<- read.csv("logFiles2020/originalFiles/profilesIS.csv", header = T, stringsAsFactors = F) #does not have inlet/outlet
> #also no inlet/outlet samples: bp, chl, or zoop
> 
> i=2
> r=32
> 
> for (i in c(3:6,9)){
>   orig<- read.csv(file.path(wrong,files[i])) #read in log file
>   new<- orig %>% 
>     mutate(sampleID = as.character(sampleID)) %>% 
>     mutate(sampleID = case_when(site == "Inlet1" ~ gsub("PML", "Inlet1", orig$sampleID), 
>                                 site == "Inlet2" ~ gsub("PML", "Inlet2", orig$sampleID),
>                                 site == "Inlet3" ~ gsub("PML", "Inlet3", orig$sampleID),
>                                 site == "Outlet" ~ gsub("PML", "Outlet", orig$sampleID),
>                                 TRUE ~ sampleID))
>   write.csv(new, file.path(right, files[i]), row.names = F)
> }
> 
> #checking output: (all good)
> newColor<- read.csv("logFiles2020/correctedFiles/colorLogFile.csv", header = T, stringsAsFactors = F)
> newDOC<- read.csv("logFiles2020/correctedFiles/docLogFile.csv", header = T, stringsAsFactors = F)
> newfiltered<- read.csv("logFiles2020/correctedFiles/filteredLogFile.csv", header = T, stringsAsFactors = F)
> newunfiltered<- read.csv("logFiles2020/correctedFiles/unfilteredLogFile.csv", header = T, stringsAsFactors = F)
> newpoc<- read.csv("logFiles2020/correctedFiles/pocLogFile.csv", header = T, stringsAsFactors = F)
> 
> #moving unaffected log files over to the correctedFiles folder: 
> move<-files[c(1:2, 7:8, 10)]
> i=1
> for (i in 1:length(move)){
>   file.copy(file.path("logFiles2020/originalFiles",move[i],sep=""),file.path("logFiles2020/correctedFiles",move[i],sep=""))
> }
> ```

Now that I've looked through, I think this was because of the very weird format of the moieties table, where some of the column headers are sites like Inlet1, Outlet, etc. and some of them are depthClasses. That's just asking for trouble, having the column names not be "parallel" per se.

I've re-written a bunch of the code and it _should_ now account for this and properly assign the depthClasses and siteNames to their proper places. But I'll keep an eye out for errors in case any pop up.

**Comment by kaijagahm** [comment]
> A helpful check based on a current snag- sampleID's generated by the entry tool didn't include a preceeding 0 for 3-digit times (resulted in _932_ instead of _0932_). Not sure if this got fixed for the 2020 Limno Entry Tool or if I coded the fix later.

This will be fixed in my current version of the entry tool by the function `formatTimeSample`, which does the following:
- Checks to make sure the time is either 3 or 4 digits. If it's some other number of digits, throws an error
- If the time is only 3 digits, appends a leading 0.
- For either the original 4-digit time or the fixed 3-digit time (now 4-digits), checks that it's a valid time: i.e. that it has the format "^[0-2][0-9][0-5][0-9]$".

**Comment by kaijagahm** [comment]
> Idea for off-limits projectIDs- If there are projectIDs that are "retired" it wouldn't be hard to make the entry tool reject them. For example, 1-12, 14, 16, 18-33, 39-40. ProjectID mix-ups don't happen frequently but I've found a few.

Addressed in most recent version of the tool. Edited the above list a little. List is now c(1:2, 4:5, 7:12, 14, 16, 18:25, 27:33, 39:40). See supportingFuns.R

**Comment by kaijagahm** [comment]
> From meeting with Randi 4/26:
> 
> * Does limno entry tool compare e.g. pH values (etc) to past data from db? (Need to know for testing). Yes--it pulls LAKES, LIMNO_PROFILES, and SAMPLES data from the db version. We'll have to set it to an earlier db version to test it on new data.
> * Space in id number randomly--sometimes, but not other times?
> * When inlet1--assigning PML in place of siteName (inlet1). So it comes out inlet1_Surface. Not good!

Should be fixed in most recent version. Let me know if this recurs.

**Comment by kaijagahm** [comment]
Closing this for now since I've created an updated version of the limno entry tool. Will re-open if more issues come up. See tool template [here](https://github.com/MFEh2o/limnoEntryTool_TEMPLATE)
