### ISSUE TITLE
SAMPLES add sample data from LIMNO_PROFILES update

### ISSUE THREAD

**Issue by kaijagahm** [MFEh2o/db#143]
Looks like the most recent update to LIMNO_PROFILES only updated the data table and didn't add samples to the SAMPLES table, so that foreign key check failed. Looks like LIMNO_PROFILES should indeed have a foreign key relationship to SAMPLES, so I'm going to go ahead and add those rows.

**Comment by kaijagahm** [comment]
I pulled the samplesIS files for 2019 and 2020 off of Box and tried to do this myself, but it seems like we don't have crew/weather information for all of the sampleID's and I don't understand why. Maybe something weird with the limno entry tool? Might be best to do this through proper channels instead of by hand.

**Comment by kaijagahm** [comment]
Pretty sure this fix gets included in the database update that @Randinotte is currently working on, though I could be misremembering--correct me if I'm wrong.

**Comment by kaijagahm** [comment]
This issue has a script started. See 'gh143_limnoProfilesSamples.R' in my archive.

**Comment by Randinotte** [comment]
I believe this is tied to a larger issue I'm trying to wrap my head around. 2019 rows in SAMPLES were edited during a fix to correct a dateTimeSample issue (currently searching through GH issues to figure out which one, update metadata isn't helpful). If I'm remembering correctly, some rows in SAMPLES had different times in their sampleID's vs. their dateTimeSample columns. I believe we needed to make an executive decision about which time to believe and might have caused this error.

Two examples: 
SAMPLES: AQ_DeepHole_20190823_1**2**30_surface_0_fishScapesLimno.20190319
WATER_CHEM: AQ_DeepHole_20190823_1**3**30_surface_0_fishScapesLimno.20190319 *matches datasheet

SAMPLES: BA_DeepHole_20190613_0**7**32_hypo_Limno.Sample.20160505
WATER_CHEM: BA_DeepHole_20190613_0**8**32_hypo_Limno.Sample.20160505 *matches datasheet
LIMNO_PROFILES: BA_DeepHole_20190613_0**8**32_hypo_Limno.Sample.20160505 *matches datasheet

**Comment by Randinotte** [comment]
This issue was related to #166, and the update for that fix (4.7.1) corrected sampleID's so that the sample info (crew/weather/comments) could be grabbed from the logs as planned. All 2020 limno profile sampleID's are now listed in SAMPLES. This is resolved with v 4.8.1 "Var(ve)iants" 2021-11-22. 

Edit: @joneslabND Are you able to close this issue? I'm neither the repo owner or issue author. Thanks!
