### ISSUE TITLE
Double-check habitats in OTU

### ISSUE THREAD

**Issue by kaijagahm** [MFEh2o/db#147]
As far as I know, nobody has (recently) done a full check on the OTU table to make sure the 'grouping' and 'habitat' columns are properly assigned. Some of this will get checked informally as part of #17, and maybe I can outsource a little bit of the checking to someone along the way before I finalize that. But someone with more knowledge than me definitely needs to deal with the habitats.

**Comment by kaijagahm** [comment]
Began a script for this. Once this database update is done, will need to re-run the script to extract the habitats. Then upload to Google Drive and send to Stuart/Chris/Randi for checking.

**Comment by kaijagahm** [comment]
@joneslabND @ctsolomon @Randinotte [here](https://docs.google.com/spreadsheets/d/1r4QmqU71k9zMYh7czrz97yjAZbuNUJEcpb48_f4n1jQ/edit?usp=sharing) is a google sheet for looking over habitats and groupings in the OTU table.

**Comment by ctsolomon** [comment]
@kaijagahm can you explain the color coding on the google sheet? Also - I could use a refresher on what we're using these two columns for, and what the database column descriptions say we're using them for. I know partial answers to this but not sure I have the whole scope.

**Comment by kaijagahm** [comment]
@ctsolomon Oh, sorry! The colors are just to distinguish different classifications. That bright blue is for "benthic_invertebrate" and "benthic" (because I figured those two would almost always go together and we'd want to know if they didn't), and then I gave the other habitats different colors so it's easier to skim. But if the colors are annoying for you, you can feel free to remove them.

You ask a good question about what we're using these for, and Stuart emailed me a similar question. I don't think I have a good answer. UNITS isn't much help; it just says 'type of organism' for 'grouping' and 'where the organism lives' for 'habitat'.

One use case that we've already come across is using the 'fish' grouping to pull out relevant entries in OTU for the fish entry tool. But I don't know of a use case for the bugs and other organisms. I had brought this up basically because I've been adding entries to OTU periodically, and I wasn't sure what the procedure was, if anything, for determining these classifications.

I'll put this on the agenda to discuss briefly on Tuesday.

**Comment by kaijagahm** [comment]
As of 6/8, we're going to retain the `grouping` column but remove `habitat`, assuming that there are no rows that are distinguished only by habitat.

**Comment by kaijagahm** [comment]
Since `otu` is the primary key, `habitat` is not necessary to distinguish rows. 

Removed beaver and turtle.

For 'substrate', 'otoliths', and 'no_sample_taken', checked all tables that join to OTU (found a list of these by looking at the database check script) to make sure they appeared nowhere. They don't. Removed them.

Removed 4 rows and 1 column for new dimensions of 13x346. Will need to update UNITS, SQL, and check script.

**Comment by kaijagahm** [comment]
Finalized in v 4.7.0.
