### ISSUE TITLE
BGPP (Benthic primary production dome data)

### ISSUE THREAD

**Issue by kaijagahm** [MFEh2o/db#152]
Goals:
1. Compile and organize the Benthic GPP (BGPP) data so we can start exploring patterns w/r/t depth
2. Get the organized data into the sensor database
3. Develop a reproducible pipeline to read data directly from the database into any analysis scripts we end up using.

Summary of what we know so far:
KG organized all data (2012-2020) in a folder on Box called '**BGPP Dome Data (all years)**'. (Originally, it was stored in various places on Box, including in Katie Saunders's file archive and maybe on Carly's computer. Where possible, I've left the original data in place in Katie's archive, but copied it over to this centralized folder). There are different file organizations for each year. In general, the data is broken down into "InputFiles" and "Results".

- Lakes sampled: EL, WL, FE (later years)
- InputFiles contains **DO** and **TEMP** data for all years. For 2012-2014, it also contains **PAR** measurements, but KG noted that those PAR measurements are already in the sensor db; it's **not new data**.
- The data is broken down into different light levels: generally **5%, 25%, 40%, and 60%**. 
- In 2012, EL instead has 25%, 25%a, 25%b, and 25%c. WL also has the **a, b, c replicates** for 25%, but it has other light levels as well, while EL for that year has nothing besides 25%. Presumably, this was a replication test in the first year of the experiment to measure variability within a light level, but we don't know for sure.
- For several of the years, the Results folder contains some GPP calculations using the **'bookkeeping method'** (see e.g. [this paper](https://www.tandfonline.com/doi/pdf/10.1080/IW-6.4.883)). I don't know what GPPBookSystem means, as opposed to RBookSystem, and I'm not sure whether 'system' refers to the bookkeeping 'system' of calculations, or to some ecological 'system'.
- In 2015-2018, **deploy logs** are included in the individual year folders. There's also a deploy log file for 2012-2014 included in the top-level directory. I'm not sure whether we have deploy logs for 2019-2020 anywhere.
- I added a folder called CarlyScripts to include some **R scripts** that Carly sent along. She's been using these to do BPP calculations, and she thinks they're the most up-to-date versions of the calculation scripts. 
- Here are some **notes** from past conversations about adding the BPP data to the database:
[Notes for Sensor DB tables.docx](https://github.com/MFEh2o/db/files/6640391/Notes.for.Sensor.DB.tables.docx)
[Notes on MFE BPP for database.docx](https://github.com/MFEh2o/db/files/6640392/Notes.on.MFE.BPP.for.database.docx)
- The most current version of the **metadata document** for the benthic dome project is 
[benthicDomeMetadata_20171221_COComments.docx](https://github.com/MFEh2o/db/files/6640402/benthicDomeMetadata_20171221_COComments.1.docx)
     - **TO DO:** Expand this metadata document. "We'll need to expand it beyond the field and lab (download) methods. I think a brief description of the whole project and any descriptions/instructions of the BPP calculations would be useful additions." - RN
- **Eventually:** will want to put the high-frequency sensor data in the sensorDB, but put the derived BPP estimates in a table in the regular database.

> [I]t might be that we end up with data in two places - the underlying high-frequency sensor data will obviously be in the sensor database, e.g. in the table that has corrected DO data. But perhaps we would want to take the benthic GPP estimates that we derive from those data and put them in the "PRIMARY_PRODUCTION_BENTHIC" table in the main database, with a different metadata than the data that are currently in there, so that they are easily accessible without having to re-run the metabolism model. That might be worth considering, especially if it wouldn't require a major overhaul of the structure of "PRIMARY_PRODUCTION_BENTHIC" -CTS

**Comment by kaijagahm** [comment]
I did some work on getting my head around all the BGPP data. Questions:

1. This data is different from the PRIMARY_PRODUCTION_BENTHIC table in the regular database, which only has 2011 (BGPP project starts in 2012). We might want to put derived estimates in PPB table eventually (see CTS note above), but for now I can ignore that. Different project.
2. Carly notes that the 2019 and 2020 "raw" data she sent has actually already been through B3 (That's the data I put in the BGPP Box folder.)
3. **Scripts:** eventually will have two types. 1) Scripts to process the raw data before it goes into the sensor db (B3 is another step in this process), while the unprocessed data goes in _RAW tables, and 2) eventual scripts to pull data from the sensorDB and use it for analysis (e.g. the R scripts in CarlyScripts).

Randi's notes: 
- "potential inconsistencies between data types available in each year"
- "B3 output files doens't have dated folders, but pre-B3 sensor data will be stored in a winding folder structure that ends in dated folders."
- Randi will inventory all the data we have to figure out what types of data are present.
- "It seems like we have final B3 output for 2019-2020 but might only have original pre-B3 data for earlier years. It's probably a mix of both."

> A text file called lakeIDYYYY.txt" indicates that it is corrected output from B3 and goes into *_CORR table. These files will contain columns about change codes. I would expect this file to contain data from all dome deployments for that lakeYear (maybe three different deployments). The files "lakeIDYYYY_Raw.txt" are B3 output but do not have any corrections made or change code columns. They go into *_RAW. So, text files of either type indicate that the file has gone through B3 and has been QC'd. IF a folder structure looks quite different and terminates in a YYYYMMDD folder containing daily text files and one Cat.TXT file, it is the "raw" data straight out of the sensor and has NOT been through B3. Each YYYYMMDD folder contains data for one deployment about a week long.

Additional comments from Randi about the folder structure: 

> Folder structure is relatively important because of the way the B3 input formatting script mines the data. B3 can really only handle input files from individual lake+site+depth (ex. WL_Benthic_60%) so the scripts make individual lake+site+depth files. Here's a screenshot of Slide 5 from the instructions powerpoint. This shows the folder structure that the B3 input script is expecting. I know Chris mentioned that the folder structure changes between years, so I will either adapt the script or need to rearrange the folder structure for years that don't fit this format. I think I'm better suited to reorganize the folder structure than Kaija, so I can do that (making sure to leave an untouched copy that's not rearranged).
![image (2)](https://user-images.githubusercontent.com/37053323/121735900-c4421d00-cac4-11eb-957a-552c0287815c.png)

**Comment by kaijagahm** [comment]
The plot thickens!

KG:
> so, I copied the data all together in a new folder [Note from present Kaija: this folder is the BGPP folder that I was talking about at the beginning of this issue.]: https://app.box.com/folder/135484616045 (the files also still exist in their original locations, which Chris indicated in his original notes doc). But what I'm still confused about is the folders in the OneDriveArchive, like this one: https://app.box.com/folder/113814920760. There's a folder there for benthicDomes, and then inside that there are specific date folders. It looks like they're empty for 2019, but for e.g. 2018 they look like this: https://app.box.com/folder/104991481877. Is the data in there different from the data in the folder I just created, which I took from the location that Chris indicated? I'm getting kind of turned around!

**Comment by kaijagahm** [comment]
CTS chimes in to help us figure out the case of the missing just-post-B3 data:

CTS:
> Hmmm. So we're talking about data at three stages, yes?
> Raw data as downloaded from sensors.
> The output from taking #1 and running it through B3.
> A stripped-down version of #2, with data on B3 changes removed.
> And we think we have #3 but are not sure where #1 and #2 are?

RN: 

> Yes that's correct. There's technically a #1b that converts the raw data into B3 input format.

CTS:

> OK. I think I could see an argument for putting only #1 in the database and forgetting about B3, but if we're going to put #3 in the database it makes me a little nervous to not also have at least #1 available. So, that being said, maybe our goal should be to put #1 and #2 in the database (which is most consistent with what we do for pelagic data, right?), or #1 and #3 if that saves us a lot of work having to re-run everything through B3.
> I say that with some trepidation about sending you off on a wild goose chase Randi. Would it be reasonable to put an initial time limit of a couple hours on searching for the raw data, and then re-evaluate strategy if you haven't found anything in that time? Folks like me, Stuart, others might also be able to help by suggesting where to look first - for instance, data from early years might be in Coloso files.
> Let me know if you have reservations about that plan - you know better than I do how much of a goose chase it might be and what else is on your plate right now.

**Comment by kaijagahm** [comment]
And that is where we left it. So far, @Randinotte has dug through a bunch of computers/hard drives and hasn't had any luck coming up with the raw data. 

So far:
- Checked Jim Coloso's old computer; nothing. Found April benthic data from Sean's folder--that's new data that we hadn't already accounted for.
- Will look on the UNDERC lab computer. 
- Will keep notes on where she's looked and what she finds.

If Randi can't find any more benthic dome data, we'll circle back with @ctsolomon about how to proceed.

**Comment by kaijagahm** [comment]
Randi hasn't been able to find any more data, and we think we probably just don't have it. @ctsolomon might do a little more digging when he's up at UNDERC, but for now we decided that I should move forward with pulling the data together.

I worked on it a bit and relatively easily pulled everything together. Here's a screenshot of the first few rows of the table I produced: 
<img width="617" alt="Screen Shot 2021-06-17 at 8 29 17 PM" src="https://user-images.githubusercontent.com/37053323/122488677-f7e0e380-cfab-11eb-8f90-7a7501c72a7d.png">

(the year column will go away)

Sent to Chris for comments/edits.

Another thing of concern:
**All** the 2016 and 2017 data seems to be... missing?? Both the datetimes and the actual DO/TEMP data is not present. I haven't done enough digging to be 100% sure that this is all a problem with the original data, vs. a problem with how I read it in, but I can see that at least for some of the files on Box, the measurements are all NA. 

Ran this by Chris too.

**Comment by kaijagahm** [comment]
Okay, most of the above problems with missing data were due to errors reading the files in and specifying column types with `readr::read_csv()` and the `col_types` arg.

Going year by year, I completed an updated workflow for reading in and reformatting/compiling the data for all years.

- The R code that I used to do this is [BenthicDomeDataProcessing.20210709.Rmd](https://app.box.com/file/831834497710), and it lives in my working folder on Box. To see how I resolved the issues with NA's, and different formats between years, see this code.
- The data I read in are stored in [Box/MFE/BGPP_DomeData/](https://app.box.com/folder/135484616045). I made a copy of that folder and stored it in my working folder, under [data/inputs/BGPP_DomeData](https://app.box.com/folder/141106886279), so that I could more easily pull data into the .Rmd script. 
- Also in the BGPP_DomeData folder, there are some documents I created that should help you understand the process. To orient yourself, start with [BGPPDomeData_Diagram_Explainer.pdf](https://app.box.com/file/834726499336). The diagram at the top shows the pipeline that the benthic dome data goes through. I numbered each of the steps (1, 1.5, 2, 3, 3.5, 4), and *those numbers are used consistently throughout the rest of the folder*, including in the names of the subfolders for each year, which contain data from the corresponding step.
- The table portion of [BGPPDomeData_Diagram_Explainer.pdf](https://app.box.com/file/834726499336) shows which data are present/missing for which years, and the file tree portion explains more about the structure of the BGPP_DomeData folder.
- The metadata document, [benthicDomeMetadata_20171221.docx](https://app.box.com/file/834716188625), also contains some notes about data processing. It talks about which data are found in the RAW and CORR database tables, as well as how I dealt with trimming the data to the deploy/retrieve datetimes for the sensors. In addition, this document discusses field methods for the benthic domes.
- Finally, I created three database tables. BENTHIC_DOME_DEPLOY_LOG contains deployment/retrieval information for the sensors. The `deployID` column is the primary key, and it links to the other two tables (all data from each sensor deployment is attached to a `deployID`). BENTHIC_DOME_CORR contains B3-corrected data, which we have for all years (though we don't have change codes for all years--see the metadata document for details). BENTHIC_DOME_RAW contains uncorrected/raw data, which we don't have for all years. Both RAW and CORR data have been trimmed to deploy times.

**Comment by kaijagahm** [comment]
This issue pending discussion in the 7/20 meeting; then can be closed if there's no further work to be done.

**Comment by ctsolomon** [comment]
There are several dome deployments that are recorded in BENTHIC_DOME_DEPLOY_LOG but either don't show up, or are not labeled with the correct deployID, in BENTHIC_DOME_CORR. These are:
```
> setdiff(deployLog$deployID,unique(d$deployID))
 [1] "FE-25-20190603"   "EL-25-20120618"   "EL-25-20120618-a" "EL-25-20120618-b" "EL-25-20120618-c" "EL-25-20120801-a"
 [7] "EL-25-20120801-b" "EL-25-20120801-c" "WL-25-20120618-a" "WL-25-20120618-b" "WL-25-20120801"   "WL-25-20120801-a"
[13] "WL-25-20120801-b" "WL-25-20120801-c"
```
In at least one case, I suspect that the data are in BENTHIC_DOME_CORR but are not labeled with the correct deployID. The plot below shows DO data that are recorded in BENTHIC_DOME_CORR as deployID="EL-25=2012-08-01". This looks to me like data from several sensors, suggesting that all of the replicates for that lake/light level/date (including "EL-25-20120801-a", "EL-25-20120801-b", and "EL-25-20120801-c") were labeled simply as "EL-25=2012-08-01".
![image](https://user-images.githubusercontent.com/8375012/132737193-f4b79c24-44db-4fc3-b116-58eb5508c8a7.png)

**Comment by ctsolomon** [comment]
Also, deployID "WL-25-20120716" in BENTHIC_DOME_CORR looks like it should actually be several replicate deployments; replicates a, b, c, and NA are present (and thus if you look at the portion of this table corresponding to deployID="WL-25-20120716" there are four rows for each time point).

**Comment by cwbeltz** [comment]
From weekly meeting on 2022-02-02: For the single 2019 dome noted above (FE-25-20190603), @ctsolomon and @joneslabND suggested adding a note in the comment section of the deploy log that this dome did not exist/was pulled early based on comment in [BenthicDomesLog2019.xlsx](https://app.box.com/file/831001448998) that “One dome (unknown maybe 40% or 60%) pulled up accidentally on 2019-06-06 around 10am.”

This resolves 1 of the 14 deployIDs mentioned in 2021-09-21 comment above.

**Comment by cwbeltz** [comment]
From weekly meeting on 2022-02-23:
1) For WL 2012 deployIDs, append replicate letter to end of deployID.
2) For EL August 2012 deployIDs, append replicate letter to end of deployID.

Continue to look for June 2012 EL data. Confirm 2012 light levels of only 25%, by checking 2013 EL data for 5%, 25%, and ~40%(2x).

**Comment by cwbeltz** [comment]
2012-2020 BGPP data has been uploaded to the sensor database with update to 6.2.0.
