### ISSUE TITLE
OTU water mites

### ISSUE THREAD

**Issue by ctsolomon** [MFEh2o/db#157]
We have two entries for water mites in OTU. One has “hydrachnidae” in OTU column, which is incorrect spelling. This row should be removed from OTU. The other has “hydrachnidiae”, which is correct. The correct row should be retained but edited so that orderTax=Trombidiformes, commonName=mite, OTU= hydrachnidiae, and the other taxonomic columns are NA or unknown.

**Comment by cwbeltz** [comment]
fix completed locally. Waiting until after the Wednesday (12/08) meeting to update MFEdb.

**Comment by cwbeltz** [comment]
check all tables for usage of the incorrect spelling ("hydrachnidae") in 'otu' and 'orderTax' columns.  Located one record for sample WL_NW_20200622_0000_sediment_1_zoobenthos.Sample.20110714 in BENTHIC_INVERTS. This should likely be corrected. 

I can correct, but I did notice that the family is also listed as "hydrachnidae" and wanted to confirm that taxonomy should be changed to align with fixed OTU table terminology/taxonomy listed in original issue for orderTax, commonName, OTU, and NA/unknown for other columns.
<img width="1454" alt="Screen Shot 2021-12-06 at 4 42 43 PM" src="https://user-images.githubusercontent.com/32374186/144928140-6c939434-bfce-4bb5-8bf5-55fd0962467f.png">

**Comment by cwbeltz** [comment]
@ctsolomon Should I change the sample information for WL_NW_20200622_0000_sediment_1_zoobenthos.Sample.20110714 to align with the suggestion in original issue? This would remove the family-level information and replace it with NA, among the other changes.

**Comment by cwbeltz** [comment]
after looking a bit more into taxonomy, it looks like the orderSample=hemiptera (which may be accurate), which doesn't align well with the change I previously suggested based on original issue. I can certainly correct the spelling in the family and otu fields, but that will map inverts from two different orders to the same "otu" of "hydrachnidiae". I may need some additional guidance on taxonomy here.

**Comment by ctsolomon** [comment]
Thanks @cwbeltz. @aadey1, can you weigh in here quickly? See screen shot above from Chris: for invertID WL_NW_20200622_0000_sediment_1_zoobenthos.Sample.20110714_4, the orderSample is hemiptera but family and otu column suggest this is a water mite. Can you check photos or other records and confirm one way or the other? I suspect it's a water mite with wrong info in orderSample column. If it is a water mite, then @cwbeltz you can go ahead and change taxonomy fields to match my comment at the top of this thread.

**Comment by cwbeltz** [comment]
@ctsolomon It also looks like the "hydrachnidae" spelling is in the FISH_DIETS dataset as well. Should I change these 8 records to the updated, "hydrachnidiae" spelling?
<img width="1524" alt="Screen Shot 2021-12-13 at 12 27 51 PM" src="https://user-images.githubusercontent.com/32374186/145860210-9c316de4-fdc4-44fe-af40-202e1fe32786.png">

**Comment by aadey1** [comment]
@ctsolomon and @cwbeltz it appears in the photo that this is a water mite that should match the original format that you were both discussing above. It should not have the order as hemiptera here.

**Comment by cwbeltz** [comment]
Thanks @aadey1! Will make the change.

**Comment by cwbeltz** [comment]
Changes to OTU, BENTHIC_INVERTS, and FISH_DIETS approved by @ctsolomon and @joneslabND at our weekly meeting today (2021-12-15). Updated DB as part of v5.1.1 on 2021-12-15.
