### ISSUE TITLE
Limno entry tool doesn't supply inlet/outlet data to samplesIS.csv

### ISSUE THREAD

**Issue by Randinotte** [MFEh2o/db#167]
While trying to pull sample information for the first 2021 data update, I found that the Limno Entry Tool no longer generates rows in samplesIS.csv for inlet/outlet samples. There are some depthClass=="surface" samples generated, but they are at the site DeepHole. At first I assumed that these surface DeepHole samples were for the 0m PAR measurement (the only data point collected at depth 0m), but those profile points have the depthClass=="point" and those rows do exist. 

I think this means that the Limno Entry Tool _attempts_ to generate rows for inlets/outlets when they're sampled, but it assigns the site "DeepHole" instead of the correct "Inlet1", "Inlet2", "Inlet3", or "Outlet". 

This is further evidenced by the first instance when the MO inlets were sampled on 2021-05-24, and samplesIS.csv has three duplicate rows for the sampleID "MO_**DeepHole**_20210524_1000_surface_0_Limno.Sample.20160505". Instead, there should be three rows, one each for:

"MO_**Inlet1**_20210524_1000_surface_0_Limno.Sample.20160505"
"MO_Inlet2_20210524_1000_surface_0_Limno.Sample.20160505"
"MO_Inlet3_20210524_1000_surface_0_Limno.Sample.20160505"

Additionally, the only "surface" rows generated are for lakes with inlets/outlets, indicating that it's not generating "surface" rows at sites that don't have them. I would need to look through past samplesIS.csv's to see if a row is generated for each inlet/outlet even if the stream is not sampled because it's dry.

I don't think that I'm the best person to tinker with the Limno Entry Tool, but I'm comfortable fixing the 2021 samplesIS.csv to make it useable. This would allow me to keep working on early 2021 database updates without waiting for an entry tool fix. Maybe this is an easier first fix for @cwbeltz to attempt when he gets to working on the Limno Entry Tool so that it works for next year?
[samplesIS.csv](https://github.com/MFEh2o/db/files/7629727/samplesIS.csv)

**Comment by Randinotte** [comment]
The siteName for whole lake staff gauges should be "WholeLake", but samplesIS.csv has assigned it as "DeepHole". 

As is (incorrect):
WL_DeepHole_20210519_1103_**S**taff_0_Staff.Gauge.Sample.20140319

Should be (correct):
WL_WholeLake_20210519_1103_**s**taff_0_Staff.Gauge.Sample.20140319

Edited: "Staff" should be lowercase as well (all depthClasses are lowercase except PML)

**Comment by Randinotte** [comment]
Update on " I would need to look through past samplesIS.csv's to see if a row is generated for each inlet/outlet even if the stream is not sampled because it's dry."

Answer: Yes, there should be a row generated, and the height gets recorded as "NA". In 2021 I incorrectly left those dry streams blank on the datasheets, so no sampleIS.csv rows were generated at all. I made this correction for my updates to STAFF_GAUGES and left instructions so that future datasheet users would enter "NA".

**Comment by Randinotte** [comment]
My fixes to use the sampleIS.csv from 2021 "as is" are in my script /workup2021/Staff Gauges/compileStaff_gauges_20211228.R (will put on box soon in my archive).

**Comment by Randinotte** [comment]
The compileStaff_gauges_YYYYMMDD.R script is capable of this, but it really seems like a job for the limno entry tool: Staff heights (WholeLake staffs and stream staffs) are not supplied in an output file. They are listed as depthTop = 0 and depthBottom = 0 in samplesIS.csv. To get them, I had to write a for loop to run through all the sampleSheets (digitized datasheets) and pull the staff heights from each sampleSheet. Like I said though, it works as is, just would be a nice feature to add if someone's already tinkering with the staff heights/stream output data from the tool. An easy fix would be to have the depthTop to be the actual data value, but that gets complicated because WholeLake staffs are entered in decimal feet and stream staffs are in cm.

**Comment by joneslabND** [comment]
I think this is now fixed with the current limno entry tool updates that allow stream only entries.
