### ISSUE TITLE
minor correction FISH_INFO

### ISSUE THREAD

**Issue by ctsolomon** [MFEh2o/db#170]
For fishID=='WL_WholeShoreline_20160523_2040_AN_MarkRecap.20120228_26', a '1' is recorded in the mortality and removed columns. But this same fish (as indicated by the tag) is recaptured several more times, most recently 2018-07-02, when it was marked again as removed and an otolith was taken from it (so it was really dead at that point). Amaryllis looked back at the field data sheet for the 2016-05-23 handle of this fish, and based on the comments and other clues it looks like this fish was in rough shape when it was released on that day, and the crew presumed that it was dead. But it must have recovered in the end.

So, these changes need to be made for fishID WL_WholeShoreline_20160523_2040_AN_MarkRecap.20120228_26
-Change 'mortality' and 'removed' columns to NA for fishID 
-In comments column, add "Dropped in lake and sank like a rock, presumed mortality"

**Comment by cwbeltz** [comment]
addressed as part of update v5.3.3.
