### ISSUE TITLE
sensorDB BENTHIC_DOME_CORR and BENTHIC_DOME_DEPLOY_LOG - column formatting etc

### ISSUE THREAD

**Issue by ctsolomon** [MFEh2o/db#178]
The columns in these tables (and possibly in related tables like BENTHIC_DOME_RAW, I haven't looked yet) could use some tidying in the way that they are stored and the way that sensordbTable() reads them in to R. Here are issues I have seen so far as I have started to work with these tables:

1. In BENTHIC_DOME_CORR and BENTHIC_DOME_DEPLOY_LOG, some columns that should be numeric are read into R as character. This includes lightLevel, targetDepth_m, actualDepth_m.
2. Note that the targetDepth and actualDepth columns have "_m" appended to them in BENTHIC_DOME_CORR but not in the log table. We should use the same format in both places. My preference would be not to include the _m since we generally don't include units in the column name elsewhere in the database.
3. In BENTHIC_DOME_CORR and BENTHIC_DOME_DEPLOY_LOG, the replicate column has some blank entries that are recorded as "". These should be changed to NA I think.

**Comment by ctsolomon** [comment]
Also:

4. Date/time columns in the deployLog table (including dateTimeDeploy, dateTimeRetrieve, and the four ...SatBag columns) are read in to R as character rather than as POSIX

**Comment by cwbeltz** [comment]
All corrections are complete and uploaded to Box as part of the 6.3.1 update to the sensorDB. 2 and 3 were fixed within the sensorDB tables, while 1 and 4 were corrected through updating the sensordbTable() function in the MFEutilities package ([PR#13](https://github.com/MFEh2o/MFEUtilities/commit/f45ed61efc0429e92e3aa3390cd4a2938778769c)).
