### ISSUE TITLE
LAKES - lat long

### ISSUE THREAD

**Issue by joneslabND** [MFEh2o/db#26]
A lot of the lat-long coordinates are rounded to too few digits. Also CYB longitude is missing a negative sign.

**Comment by katiesaunders** [comment]
I corrected CYB's longitude.

**Comment by kaijagahm** [comment]
Have corrected several of these based on the NHLD data or based on WBIC information. But we're now wondering whether we want a standardized protocol for how to pull lat/long for lakes. As of today, I've selected a random sample of 10 lakes and looked into lat/long in the dataset, on the WBIC page, off of Google Maps, and from an online UTM converter.

Findings so far: Google Maps is both inaccurate and difficult to use. WBIC is much easier to use, and fairly accurate, though sometimes it deviates. The only lakes that have UTM coordinates seem to be the ones with very few decimal places to begin with, so generally the UTM conversion matches those few digits, although I don't think that really tells us anything. UTM conversion is a bit of a pain, but not too bad.

* Note also that the UTM coords in LAKES are recorded as Easting and... Westing? That can't be right. I think that should be changed from W to N.

Next: take that random sample of 10 lakes and look for them in the NHD dataset. See how easy/hard that is, and whether the existing lat/long coords agree/disagree with the ones found in that dataset.

**Comment by joneslabND** [comment]
I think we should not bother with UTM coords and therefore wouldn't need the convertor unless there is some current or historical reason for UTMs I'm not thinking of.

**Comment by kaijagahm** [comment]
Next to do: summarize thoughts about standardizing a protocol for lat/long.

**Comment by kaijagahm** [comment]
I summarized what I've done so far for lat/long in the meeting on 6/30/2020. Stuart and I discussed setting up a tool in R that would allow people to look at polygons overlaid on google maps to find their lake and find the associated row in the NHD dataset. He and I are going to set up a meeting to talk about this next week.

Meanwhile, still waiting for some updates from Patrick on some of the missing lakes.

**Comment by kaijagahm** [comment]
Tool has been built: it's over at https://github.com/MFEh2o/lakeLatLongFinder. 

Going to track issues regarding enhancements/fixes to that app over in the other repo: https://github.com/MFEh2o/lakeLatLongFinder/issues

**Comment by kaijagahm** [comment]
Closing this for now--we're going to have someone (not me) go through and fix all the lat/long coordinates based on the new tool.

**Comment by kaijagahm** [comment]
Closed with db version 3.5.0, 9/30/2020
