### ISSUE TITLE
MANIPULATIONS - beaver dam removals on Morris inlet #2

### ISSUE THREAD

**Issue by joneslabND** [MFEh2o/db#28]
This seems like an ok place to keep a record of these. We should try to figure out when some past removals happened. One is mentioned in Zwart's pulse-lags paper. 

We did a removal on June 7, 2019.

**Comment by kaijagahm** [comment]
[This paper](https://www.fs.fed.us/nrs/pubs/jrnl/2016/nrs_2016_zwart_002.pdf) mentions one of the Long Lake curtain manipulations (the second one, I think) but as far as I can tell doesn't mention a beaver dam removal. Is there a different Zwart paper I should be looking at, @joneslabND?

**Comment by kaijagahm** [comment]
I started a MANIPULATIONS table, putting together information from the docs in Katie's folder on Box. 
https://docs.google.com/spreadsheets/d/1mNeHgtWXmfsIz1ddV4qcaxioCUyx_NeB6q6PSHPglZw/edit?usp=sharing. See also #6 .

**Comment by joneslabND** [comment]
> [This paper](https://www.fs.fed.us/nrs/pubs/jrnl/2016/nrs_2016_zwart_002.pdf) mentions one of the Long Lake curtain manipulations (the second one, I think) but as far as I can tell doesn't mention a beaver dam removal. Is there a different Zwart paper I should be looking at, @joneslabND?

That paper refers to the 1st and 2nd curtain, but not the third that we added in 2018. The beaver dam removal may be mentioned here:
https://www3.nd.edu/~sjones20/ewExternalFiles/Zwartetal2017_Ecosystems.pdf

**Comment by kaijagahm** [comment]
At the meeting 7/7/2020 we decided that routine beaver dam maintenance (e.g. removing a few sticks every couple weeks) should not count, but larger or more unusual removals should.

**Comment by kaijagahm** [comment]
> The beaver dam removal may be mentioned here:
> https://www3.nd.edu/~sjones20/ewExternalFiles/Zwartetal2017_Ecosystems.pdf

@joneslabND did you mean to link to a different paper? This looks like the same one I referenced in a previous comment, which refers to the Long Lake curtains but not to any beaver dams.

**Comment by joneslabND** [comment]
@kaijagahm This paper includes East Long Lake, but is not about the curtain manipulation. It describes water and carbon inputs to East Long, Crampton, and Morris. I thought jake might have mentioned beaver dam removal in the paper, but it doesn't look like it. You could ask him about this. It is either in 2013 or 2014 that this happened.

**Comment by kaijagahm** [comment]
This might be low-hanging fruit to work on at the 1/26 meeting.

**Comment by kaijagahm** [comment]
This is redundant with #6. Closing.
