### ISSUE TITLE
BENTHIC_INVERTS data problem

### ISSUE THREAD

**Issue by ctsolomon** [MFEh2o/db#34]
For invertID="WL_N_20160511_0000_sediment_1_zoobenthos.Sample.20110714_10", taxa is recorded as chironomidae but orderSample is trichoptera.

**Comment by ctsolomon** [comment]
Couple others:

invertID="EL_SE_20160511_0000_sediment_3_zoobenthos.Sample.20110714_35", taxa is oligochaeta but orderSample is diptera

invertID="EL_N_20160511_0000_sediment_3_zoobenthos.Sample.20110714_16", taxa is oligochaeta but subclass is nematoda.

**Comment by kaijagahm** [comment]
UpdateID associated with the one that got changed here is "bugFix.20181018", which was never added to UPDATE_METADATA. However, it was created in Alex's script called bugTableFix_20181018.R, and he made a note that he had to do that update. 

I will add updateID == "bugFix.20181018" to UPDATE_METADATA in my script meta_3.3.0.R, with a note that this was Alex's update.

Remains to be discovered what's going on in this script that changed the taxonomy of one of the inverts, though. Come back to this.

**Comment by kaijagahm** [comment]
Alex changed one invert from "nematode" to "oligochaeta". Seems that this was incorrect? Check with someone who actually knows invert taxonomy.

If we end up having to change this one back, we will also have to recalculate its dry mass. Presumably the reason it was changed in the first place was that the original taxon wasn't included in the DRY_MASS_EQUATIONS table. So either we'll have to be content with leaving dryMass blank, or we'll have to find a new taxon to assign.

**Comment by ctsolomon** [comment]
I went back to our photo archives of samples.

For invertID="EL_N_20160511_0000_sediment_3_zoobenthos.Sample.20110714_16", this looks like a nematode to me. By our new controlled vocab (see issue 31), correct naming for this should be "nematoda" in both the "supergroup" and "otu" columns, NAs in other columns.

Note that invertID="EL_N_20160511_0000_sediment_3_zoobenthos.Sample.20110714_15" (the previous invert in this same sample) is also recorded as nematode/oligochaeta, and should also get corrected.

For invertID="EL_SE_20160511_0000_sediment_3_zoobenthos.Sample.20110714_35", "diptera" in orderSample appears to be a drag-down error. This is certainly a worm based on the photo, and so we should stick with the oligochaeta identification. By our new controlled vocabulary this should be "oligochaeta" in both the "supergroup" and "otu" columns, NAs in other columns.

For invertID="WL_N_20160511_0000_sediment_1_zoobenthos.Sample.20110714_10", this is certainly a trichopteran. I'm attaching the photo here - it's the second individual from the right. It might be useful to ask Shun if he can ID that to genus or family from the picture, since he's the one who originally ID'd all these bugs. If he's not able to do that we could ask Amaryllis, and if neither can do it from the photo we can just leave is as "trichoptera" in the "orderSample" and "otu" columns.

It occurs to me also that we should get all of the archived bug photos into one place. I'll make a new issue for that.

**Comment by kaijagahm** [comment]
Sent a Slack message to Amaryllis to ask her if she can help ID that trichopteran to family or genus.

**Comment by ross-alex** [comment]
Hmmm, can’t really recall on that one. I imagine it’s the similar body plan idea you mentioned, and the fact that there were only 5 nematodes in the entire database. If you find dry mass equations for nematodes though that sounds like the better solution. 

Alex

**Comment by kaijagahm** [comment]
Okay, great, thanks. Just wanted to make sure there wasn't something special that I wasn't aware of.

**Comment by kaijagahm** [comment]
Reminded Amaryllis about the unidentified trichopteran. Hopefully will hear from her soon.

Returning to Chris's problems above:
> invertID="EL_SE_20160511_0000_sediment_3_zoobenthos.Sample.20110714_35", taxa is oligochaeta but orderSample is diptera
> 
> invertID="EL_N_20160511_0000_sediment_3_zoobenthos.Sample.20110714_16", taxa is oligochaeta but subclass is nematoda.

The first one of those was fixed when I went back and checked photos. Turned out to be trichoptera. The second one we've put back to "nematoda" in supergroup. Making this match to fish diets will be a whole separate issue.

**Comment by kaijagahm** [comment]
Closing this. Remaining problems with taxonomy will be dealt with over in #31.
