### ISSUE TITLE
dbUtil.R defaults

### ISSUE THREAD

**Issue by ctsolomon** [MFEh2o/db#35]
In the dbUtil.R function, for dbTable() function, think about whether to change the default value of the argument 'dbname'.

Right now this is written as:
dbTable <- function(..., dbname=db)

One objection to that is that someone has to read the README in order to use it correctly, which I would say defeats the point of a default value to a function argument. An different option would be to make the default:
dbTable <- function(..., dbname=MFEdb.db)

Which would mean the function would work as long as the fpath argument was specified.

This might be a preference thing, we should discuss before changing.

**Comment by kaijagahm** [comment]
Discussed this at the 6/8/2021 meeting. SEJ mentioned that he tried to implement the character string as a default before and ran into some weird problems that were easier to deal with by just using the current setup.

I pointed out that the current setup forces you to write in the name of the database file you're using, which _maybe_ will encourage people to actually use the dated versions of the database. It's not a guarantee, but I worry that if the default is the undated file, people will just always use that.

Given these concerns, we're not going to pursue this change.
