### ISSUE TITLE
FISH_INFO FISH_OTOLITHS missing and duplicated fish ids

### ISSUE THREAD

**Issue by aadey1** [MFEh2o/db#38]
We noticed that this fish ID "KT_FN3_20160602_1020_FN_GonadSurvey.20160623_169 " is in the otoliths table but missing from the fish_info table

It also looks like there may be some duplicated fish IDs in the FISH_INFO table

**Comment by kaijagahm** [comment]
Re: duplicated fish ID's: 

fi <- dbTable("FISH_INFO") # get the fish info table
nrow(fi)
length(unique(fi$fishID)) # these differ, so we definitely have some duplicate fish ID's

dup_fids <- fi %>% filter(duplicated(fishID) | duplicated(fishID, fromLast = T)) # all rows with duplicated fish id's

dup_all <- fi %>% filter(duplicated(.)) # rows that are fully duplicates across all columns (12 pairs)

dup_fid_only <- fi %>% 
  filter(duplicated(fishID) | duplicated(fishID, fromLast = T)) %>%
  filter(!duplicated(.)) # rows that have duplicate fishID's but aren't duplicates across all columns. This is most of the rows. May have a different species name, or a slight difference in length, or a length value missing in one row but not the other, etc.

Two separate questions regarding duplicates, then.
1. Any reason not to simply get rid of the fully duplicate rows (one of each of the 12 pairs)?
2. What do we do about rows where there's different data for the same fish?
2a. Maybe different things for different cases. e.g. if row 1 says length =  200 but row 2 says length = NA, and all other columns are the same, we should probably keep the non-NA value. But what if there are two contradictory values?

**Comment by kaijagahm** [comment]
Re: alleged missing fishID. As of today, "KT_FN3_20160602_1020_FN_GonadSurvey.20160623_169 " is present in FISH_INFO. updateID is "tableFISHINFO2016BLG.20170927". This is not one of the duplicate fishID's. I think we can consider the first part of the issue resolved.

**Comment by kaijagahm** [comment]
Stalled on investigating the duplicates because I'm getting weird behavior from the duplicated() function: even when I do duplicated(fishID) | duplicated(fishID, fromLast = TRUE), I still get some fishID's only showing up one time, indicating that the function is somehow returning non-duplicates, or only one of the pair. Why? Going to come back to this later.

**Comment by kaijagahm** [comment]
Regarding the full duplicates: Before deleting them, Chris suggests doing the following.
1. Look at the field data sheet to make sure there aren't other rows that are missing and got somehow covered up by these rows.
2. Look at the csv or xlsx that was used to import these data into the database, for the same reason.

**Comment by kaijagahm** [comment]
Closing this issue and bumping the problem of duplicates over to #29.
