### ISSUE TITLE
db schema problems

### ISSUE THREAD

**Issue by kaijagahm** [MFEh2o/db#46]
According to the schema diagram, SAMPLES should have a lakeID column. It doesn't. Add one? Looks like lakeID is part of sampleID, so it should be relatively straightforward to extract that info.

**Comment by Randinotte** [comment]
Maybe you have noticed, but a warning because I didn't catch this right away: a handful of lakeIDs are more than two letters. So if you pull the lakeID's from the sampleIDs, save yourself the heartache and pull the whole lakeID.

**Comment by kaijagahm** [comment]
Thanks! Yeah, I did notice that, so if we decide we want to add this column back, I'll use regular expressions, e.g. take all capital letters between the start of the string and the first _, or something.

**Comment by kaijagahm** [comment]
In general: why do we have dateSample and dateTime sample columns in so many tables? Why not just dateTimeSample?

In a similar vein: LAKE_BATHYMETRY has both lakeID and lakeName, even though lakeName should be included in LAKES. Having it in two places could introduce errors.

Is there a meaningful difference between siteID and siteName?

**Comment by Randinotte** [comment]
Do you have an example of a table with siteName? I think it is the name of the location on the lake where it was sampled. For example, siteID = lakeID_siteName = WL_DeepHole. But if you have a table to point to where siteName is listed I can confirm.

**Comment by kaijagahm** [comment]
BACTERIAL_PRODUCTION_BENTHIC has a siteName column, for example. 

That would certainly make sense, if that's right! I can also look into it if you don't get around to it.

**Comment by Randinotte** [comment]
Yep, thanks for that clue. "siteName" is a location within a lake. It shows up in BENTHIC_INVERTS and NUTRIENTS too. Basically, it gives a detailed location of where in the lake the sample was taken. "DeepHole" = the deepest point in the lake, "N" = the north corner, etc.

**Comment by kaijagahm** [comment]
I guess a general question is: what are we trying to emphasize in the schema? Worth philosophizing about on Tuesday. What determines whether metadataID, updateID, sampleID, etc. get included in the boxes, when they occur in other places too? It would be good if we could have consistent rules, and maybe indicate to the user what they are.

**Comment by kaijagahm** [comment]
I've answered a lot of my own questions here and updated the database schema: see folder "Figshare" on Box. 

Can still talk about this on Tuesday before closing the issue, but I think I'm happier now that I understand it better.
