### ISSUE TITLE
MetadataID values in CHLOROPHYLL

### ISSUE THREAD

**Issue by Randinotte** [MFEh2o/db#47]
MetadataID values in CHLOROPHYLL for 2019 samples should be "Chlorophyll.20110601" not "Limno.Sample.20160505". Limno.Sample.20160505 describes the field collection for the whole sample, not the chlorophyll analysis. Limno.Sample.20160505 should stay in the sampleID but the cell value for metadataID in the table should be replaced with "Chlorophyll.20110601".

**Comment by kaijagahm** [comment]
Fixed, and wrote txt and csv files.

**Comment by kaijagahm** [comment]
There are 479 samples from 2019 that had metadataID == "Limno.Sample.20160505" ––I have changed these to "Chlorophyll.20110601". But there are also 52 samples from 2019 that have metadataID == "fishScapesLimno.20190319". Should those also be changed to "Chlorophyll.20110601", or should they be left as is?

All 52 of those are surface samples, from project 37 (fishScapes), from a variety of different lakes, taken in August and September 2019. I can provide more information if needed.

**Comment by Randinotte** [comment]
Kaija, yes, that's a good catch. Those "fishScapesLimno.20190319" should be changed to "Chlorophyll.20110601" as well. As for changing all the updateID's in the table vs. just the ones you fixed, I just change the updateIDs for any lines that I actually change.

**Comment by kaijagahm** [comment]
Roger that. So I'm changing the metadataID for all 2019 samples to "Chlorophyll.20110601".

**Comment by kaijagahm** [comment]
metadataID's changed and updateID's updated. UPDATE_METADATA updated, in script meta_3.3.0.R. Ready for db update.

**Comment by kaijagahm** [comment]
Version 3.3.0 is live!
