### ISSUE TITLE
SAMPLES inconsistencies in depthClass

### ISSUE THREAD

**Issue by kaijagahm** [MFEh2o/db#53]
Some misspellings, duplicates, spaces, etc.

Current unique values in SAMPLES are 
```
[1] "sediment"      "PML"           "point"         "Bottle"        "Hypo"          "tow"          
 [7] "Surface"       "MidEpi"        "distFromShore" "PIEZ"          "Staff"         "Epi"          
[13] "horizTow"      NA              "Meta"          "meta"          "survey "       "Bioassay1"  
```

**Comment by kaijagahm** [comment]
Should also check FISH_SAMPLES, BENTHIC_INVERT_SAMPLES, and sampleID's all tables.

**Comment by kaijagahm** [comment]
These should be changed to sediment, PML, point, bottle, hypo, tow, surface, midEpi, distFromShore, piez, staff, epi, horizTow, NA, meta, survey, and bioassay1.

**Comment by kaijagahm** [comment]
@joneslabND @ctsolomon you wanted more information about some of the depthClass values, namely NA, "survey ", and "Bioassay1".

I'm still working on finding patterns in the ones that have an NA for depthClass--I'll post them here when I'm done. There are 9 rows of SAMPLES that have depthclass == "survey " and 13 rows that have depthClass == "Bioassay1". 

The former set of rows all have metadataID == "Surveying.20190509", but the updateID refers to piezometers: maybe these rows should have "piez" for the depthClass instead?
![Screen Shot 2020-07-07 at 13 00 20](https://user-images.githubusercontent.com/37053323/86816450-d2382400-c051-11ea-8236-93ce111ffdcb.png)

The latter rows have metadataID == "Limno.Sample.20140501" and dateTimeSample == "2015-10-12 16:00:00". I'm not sure what to make of this.
![Screen Shot 2020-07-07 at 13 00 40](https://user-images.githubusercontent.com/37053323/86816489-dd8b4f80-c051-11ea-9166-671b15dc2a58.png)

Do you have any thoughts?

**Comment by ctsolomon** [comment]
Re depthClass="survey" - these do look to me like they could be piezometer samples of some kind, for the reasons you give and because I think the "U1", "U2", etc. siteIDs were what we gave to "upland" piezometers. If these are the same kinds of samples that we take from piezometers under the "piez" depthClass then we should probably change depthClass to "piez" for these. We should check first whether they might be a different kind of sample - like a hydraulic conductivity test or something like that.

I'm not sure about the Bioassay ones - I would guess these might be from a smaller experiment that a grad student or undergrad did. Stuart might know from the info you've provided; if not, it could be useful to see what kinds of data are associated with those sampleIDs in the database.

**Comment by joneslabND** [comment]
At one point we surveyed (measured elevation of peizometers) and that could be what "survey" is referring to. Do we know whether there are any data associated with these sample IDs?

These do look like they are associated with an experiment... If these are samples that we put into bottles for a bioassay then we should change the depthClass to "surface" or "grab" (can't remember what we use. If we think these samples came from bottles that were previously sampled then, I'm not sure what to do with them... I can look for a datasheet on these.

**Comment by joneslabND** [comment]
I was looking through metadata files on Box and there is a peizometer survey metadata file and a peizometer survey table. If these samples with depthClass survey are associated with data in the peizometer survey then I agree the depthClass could be changed to peiz.

**Comment by kaijagahm** [comment]
@joneslabND @ctsolomon you were right about the "survey" depthClasses being from the upland piezometer surveys--the only data associated with that depthClass was from the piezometer survey table. So I've changed that to "piez".

Regarding the "bioassay" one: there are 14 sampleID's that have that depthClass. All are from 2015-10-12, and all are associated with the metadataID "Limno.Sample.20140501". I looked through the metadata doc and couldn't immediately find an explanation for what "bioassay" refers to, but maybe someone who understands the methods better than I do would have better luck. The database data associated with these sampleID's is from the DOC table, if that helps.

**Comment by ctsolomon** [comment]
@joneslabND do you remember what these are? From fall sampling in 2015. Inlet, outlet, and deep hole samples in CR, EL, WL, HB, MO.

Here are a few lines of code that bring up the relevant lines from DOC and SAMPLES (along with some unrelated lines in SAMPLES):
d <- dbTable('DOC')
d[d$dateSample==as.Date('2015-10-12'),]
s <- dbTable('SAMPLES')
s[s$dateSample==as.Date('2015-10-12'),]

It looks like the Bioassay samples have accompanying regular samples taken earlier in the day. I'm guessing that we took samples from the lake, started bioassays, and then sampled from the bioassays. If this is right, then maybe "bioassay" (or "bottle" or "experiment" or something if we already have one of those) is the right depth class for these samples (the ones pulled from the bioassay bottles), and we need to give that bioassay procedure its own metadataID and description.

**Comment by joneslabND** [comment]
They were looking at respiration or changes in DOC concentration over time in bottle incubations. I think perhaps the original samples can stay (these are just field samples that followed the limno protocol), and then the bioassay data could be moved to a separate data file and this could be treated as an experiment?

**Comment by ctsolomon** [comment]
That sounds reasonable

**Comment by kaijagahm** [comment]
Per 7/21 meeting: Bioassays involved taking a sample from the lake, putting it in a bottle, and then resampling from the bottle several times. If we're going to take the Bioassay data out of the database and put it in a separate csv, we should make sure to include a copy of the original lake sample in that data, but also keep the original lake sample in the database, since it's also a regular lake sample.

Chris checked, and those original lake samples should already have a normal depthClass, not "bioassay1". 

The general plan on this is to assign it a separate projectID (maybe use 33 or 10 if they're in the appropriate time window?) and link to a csv of the data somewhere else (github?).

**Comment by kaijagahm** [comment]
I've separated out the bioassay data from SAMPLES (including the regular point samples that preceded each bioassay sample) and DOC, creating new tables bioassaySAMPLES.20151012.csv and bioassayDOC.20151012.csv.

@joneslabND @ctsolomon the bioassay data is already associated with project 15 (Carbon Budgets Survey (JZ5)), and the two available projectID's are 10 and 33, neither of which is particularly near 15. On second thought, I don't really see why we can't just add a note in the project description for projectID 15 and link to the separate csv files there, instead of creating an entirely new project. Is that okay?

If so, then the next question would be: where is a good place to store these bioassay csv's so we can easily link to them? Box, outside the database folder? Or maybe on GitHub somewhere?

**Comment by ctsolomon** [comment]
Feels to me like listing the experiment within the project description, as a subset of the project, makes it a little less discoverable. I can also imagine a scenario where we have multiple experiments associated with a project - in which case we might not want to list them all in a text field like that. I see the attraction of listing the bioassay experiment as part of project 15, but I think the discoverability thing should rule the day. So my vote would be to just give it the next available projectID (either 10, or whatever is the next "new" one), and make sure to make a note in the project description saying that this was a small stand-alone experiment conducted as part of project 15 that we later went back and pulled out the data for separately.

The official permanent home of the database (and the place from which anyone besides us, and ultimately perhaps even us, would access it) is the Figshare repository. So it would make sense to me to store the experiment files in that repository. I forget whether you can create a folder structure there (so that we could e.g. have a folder for experiments, with subfolders for individual experiments) - this would be worth checking. I think Alex wrote up some Figshare notes which might have some info about this, in addition to whatever you can learn from the site itself.

Let's see what @joneslabND thinks about this.

**Comment by kaijagahm** [comment]
@joneslabND before I go forward with this (separating out the bioassay data and creating a new, non-chronological projectID for it), can you opine?

**Comment by joneslabND** [comment]
@kaijagahm I agree with Chris on the projectID point. I'm skeptical that we will make more than annual updates to Figshare, but I don't actually know the process that is involved. The folder structure question would also need to be worked out before we committed to that. My other idea for where to store the data is Box. I don't think many folks outside the group will go looking for experiment data via the database.

**Comment by kaijagahm** [comment]
I've now separated out the data for this project and placed it in the Experiments folder in Box. Referred to that folder in the PROJECTS table, assigning this experiment to projectID 33. 

I've already done the database update associated with this, and I'm getting ready to push to Figshare. Note though that there's a typo in the project description for projectID 33: it refers to projectID 10 by mistake.

I'll have to decide whether this is worth fixing and re-doing this database update before pushing to Figshare (probably. ugh.) or whether I should leave it until the next db update. The problem with the latter is that this typo is actually potentially confusing, because projectID 10 now refers to a different bioassay experiment. So it's not obvious that this is a typo/mistake.

**Comment by kaijagahm** [comment]
Also need to update the metadata for the in-bottle bioassay samples. Paragraph from Jake Zwart: 

"Samples are collected with a van Dorn bottle or grab sample, per MFE standard limnological sampling procedures. Lake or stream water are filtered through 0.2 μm suporfilters to remove bacteria, and 100 mL of filtered lake / stream water are added to 125mL acid-washed and rinsed experimental serum bottles (25 mL lab atmospheric headspace). Epilimnetic lake water or stream grab sample is filtered through pre-combusted (450°C for 4 h) 0.7 μm GF/F filters to remove grazers but retain bacteria communities and 1 mL of this bacterial community is added to each serum bottle and sealed with rubber septa and crimped aluminum seal. The sealed serum bottles are incubated in the dark at 20°C. At each sampling day, 8 mL of gas headspace is be extracted with a needle and syringe from each sealed experimental bottle and analyzed on a gas chromatograph for CO2 concentration, as CO2 is the end product of tDOC mineralization. 8 mL of laboratory air is then injected back into the sealed bottles to maintain atmospheric pressure and prevent anoxia. When serum bottles are destructed, DOC concentration of the lake/stream water is estimated per MFE standard laboratory procedures. Increases in CO2 and/or declines in DOC provide estimates of DOC decomposition."

**Comment by kaijagahm** [comment]
@joneslabND a while back, when we had just started to decode what was going on with the bioassay samples, you said:

> If these are samples that we put into bottles for a bioassay then we should change the depthClass to "surface" or "grab" 

Looks like the depthClass for the original limno samples (which were then put into bottles) is "point", not "surface" or "grab". (Then the samples taken _from_ the bottles correctly have "bioassay" as their depth class).

Do you still feel that "point" should be changed to "surface" or "grab" for those limno samples, or are they good the way they are?

**Comment by joneslabND** [comment]
point is probably ok

**Comment by kaijagahm** [comment]
Leaving this as point. Updated the metadata for the bioassay bottle samples according to the above paragraph.

**Comment by kaijagahm** [comment]
No db update required here except what's already taken care of with updating PROJECTS in #57. Do need to update figshare, however.

**Comment by kaijagahm** [comment]
Closing this; the metadata update is a duplicate of #77.
