### ISSUE TITLE
SAMPLES sampleClass column?

### ISSUE THREAD

**Issue by kaijagahm** [MFEh2o/db#54]
In 7/7 meeting with @ctsolomon @Randinotte @joneslabND, discussed maybe adding a sampleClass column to account for types of samples like staff. Randi notes that this could pose problems for e.g. the data entry tool, so we may not want to go there yet, if ever.

**Comment by kaijagahm** [comment]
Will this be partially solved by the projectID's? See #94.

**Comment by kaijagahm** [comment]
@Randinotte @ctsolomon @joneslabND If we do want to do this, now would be a good time, since the limno entry tool is fresh in my mind. 

But, we already have, for each sample:
- depthClass (which often provides info about types of samples)
- metadataID (which likewise provides info about types of samples)
- sampleGroup (which, I guess, gets at project/metadata? Possibly redundant with those
- projectID (which links samples to each project).

If we want to add a sampleClass column, I think we'd have to clarify exactly what new function it's serving, and it's not clear to me that it would be helpful. I also have no memory of whose idea this was in the first place.

Does anyone feel that we should keep this under consideration, or can I close it out?

**Comment by joneslabND** [comment]
This might have been to accommodate some different sample types, but we've gone with different sample tables instead (e.g. fish and bugs)? I think it is ok to close it... I'm not sure where staff gage samples are recorded...

**Comment by ctsolomon** [comment]
Yes, I'm not sure this has come back up since last summer, so maybe that means we can do without it unless Randi remembers a compelling reason for it that we're forgetting.

**Comment by Randinotte** [comment]
I don't remember exactly why this seemed useful last year. It's possible that there are some tables where "staff" specifically would be helpful, but I just skimmed through tables and couldn't find any that made sense.

**Comment by kaijagahm** [comment]
At 6/8 meeting, we decided we don't need this. Closing.
