### ISSUE TITLE
BENTHIC_INVERTS photo archive

### ISSUE THREAD

**Issue by ctsolomon** [MFEh2o/db#59]
We have archived photos of many (most? all?) of the inverts sampled from Long Lake. Right now these are in several locations:

- 2011, 2012, 2013, 2014, and 2015 are in Chris OneDrive: 'Commons/Photo images/Benthic inverts'.
- 2015 and 2016 are in Chris OneDrive: 'Archive/Finished student files/Koizumi MSc archive/Crazy Chironomus/Bug Photos/Bug Processing Photos (UNDERC)'.
- 2017, 2018, 2019, 2020 not sure where there are. Ask Alex re 2017-2019 - maybe one of the UNDERC computers or the OneDrive folder that field crew uses while there?

Would be nice to get these all in one accessible location.

**Comment by kaijagahm** [comment]
@ross-alex do you know where the BENTHIC_INVERTS photos are from 2017-2019?

A couple questions:
- Do we want these on Box, or somewhere else?
- Any particular things I should know about organization?

**Comment by ctsolomon** [comment]
I think Box would be a fine place. I imagine (for now at least) that these are mostly for our own reference.

Re organization - if I remember, the system varies a little year to year. I think that's ok, and we could just dump each year's folder in there.

**Comment by kaijagahm** [comment]
Amaryllis has 2017 and some of 2018. Randi has a bunch more on OneDrive. Randi will put hers onto Box.

**Comment by kaijagahm** [comment]
Got 2017 and 2019 photos from Randi and Amaryllis. Amaryllis also added the 2018 photos from a laptop, but she thinks that there are probably some others somewhere, since there are far fewer for 2018 than for 2017 and 2019. Still trying to track those down.

Got photos from 2011-2016 from Chris. 

Added all photos to "Box/MFE/BENTHIC_INVERTS photo archive"

So, just waiting on a few more photos from 2018, and any from 2020 (do those exist yet)? And then we'll be done.

**Comment by kaijagahm** [comment]
Uploading photos from 2012, 2016, and 2015. Waiting on the rest of the 2018 photos from Randi.

**Comment by kaijagahm** [comment]
Randi will finish uploading the 2012 photos if she can get her computer to cooperate. 

Stuart and Randi will check a couple more places to see if we can find the 2018 photos. If we can't, then I'll need to write a readme or similar to document which photos are missing, maybe by comparing it to the data that's in the database.

**Comment by kaijagahm** [comment]
2012 photos are uploaded. Still need to find the rest of the 2018 photos.

**Comment by ross-alex** [comment]
Hey Kaija, 

Have you been in touch with Matt Faragher or Danny about 2018 photos yet? They were the two that worked up the bugs that year and would have the best idea where missing photos would be. If you need their emails, let me know. 

Alex

**Comment by kaijagahm** [comment]
All bug photos are uploaded except for the remaining 2018 ones. @Randinotte is going to look through the bug laptop when it's not being used to see if they're on there.

**Comment by kaijagahm** [comment]
Reach out to Danny and Matt, once I get their contact info from Randi or Chris/Stuart. 

Need to make a note somewhere about where photos are stored: maybe in the column descriptions in UNITS.

**Comment by kaijagahm** [comment]
Emailed Matt and Danny 8/20

**Comment by kaijagahm** [comment]
From Matt and Danny:
- Neither of them have any photos saved on their personal computers
- Matt remembers uploading everything to OneDrive. Randi and Alex contacted him a year and a half ago to track down some photos (zooplankton, not inverts), which they eventually found on OneDrive. 
- Danny sent me a pdf describing the methods and file organization they used for their photos. There apparently should be a folder called "Summer 2018 UNDERC" which in turn contains longDiets. I can't find either of these, nor can I find any of the subfolders listed. Where did these go? Note: when I search "longDiets" in OneDrive, a result pops up, but then it says the item no longer exists or I don't have permission to view it. Is there perhaps another enclave of OneDrive that I can't access?

I'm attaching the doc here.
[Matt and Danny's Summertime Metadata.docx](https://github.com/MFEh2o/db/files/5115225/Matt.and.Danny.s.Summertime.Metadata.docx)

**Comment by kaijagahm** [comment]
Randi has located the rest of the 2018 photos and will be uploading them soon. Yay!

**Comment by Randinotte** [comment]
Uploaded the remaining photos from 2018 to the archive. I compared the list of photos to the full list of site names to make sure that there weren't any pictures missing. In all cases but one, if there isn't a photo from a certain site/depth (e.g. N8), that means there were no bugs counted. I determined that by checking BENTHIC_INVERTS for observations from the sites of the missing photos and found no observations for those photos. The one exception, FE_N_20180723_1000_sediment_8_zoobenthos.Sample.20181114, has no photo in the 2018 archive but has 48 observations listed in the table (1 ephemoroptera and 47 chironomous). I checked through the 2018-07-23 folder to see if any photos of numerous chironomids were possibly mislabeled but I didn't see anything obvious.

One error/typo became evident: In BENTHIC_INVERTS, samples were listed with the date "2018-09-27" but the photo folder was named "2018-09-28". The the excel entry file for 2018 has them listed as they are in the db table, so I corrected the photo folder names in Box.

**Comment by kaijagahm** [comment]
Great, thanks! I don't know what to do about those missing photos. Maybe they just weren't taken for that date. @ctsolomon @joneslabND do you think we should look more for those photos, or should we accept that they're missing and call this closed?

**Comment by ctsolomon** [comment]
The missing photos are a very small proportion of the total number of bugs that we sample - I think it's fine to accept them as missing and move on.

**Comment by kaijagahm** [comment]
Sounds good. I'm closing this now. Hooray!

**Comment by kaijagahm** [comment]
Note that the 2011 photos are still a mess, and many seem to be missing. But we've decided that's not worth putting a lot of time into right now.
