### ISSUE TITLE
FISH_SAMPLES time discrepancies (minnow traps AND other samples)

### ISSUE THREAD

**Issue by kaijagahm** [MFEh2o/db#60]
Looking at the minnow trap samples in FISH_SAMPLES (specifically, the ones with the metadataID "MinnowTrapSurvey.20120228") and subtract dateTimeSet from dateTimeSample, we get some negative numbers of hours that the traps were deployed. See the text file referenced below. This doesn't make sense. What's going on?

> @joneslabND unfortunately, the minnow trap deployment times don't seem to be straightforward. [Here's](https://github.com/MFEh2o/db/files/4926739/MT_deploy_times.txt) a text file that shows deployment times for each year. The column `n` is just the number of rows in FISH_SAMPLES that had that deployment time--this may or may not be a useful metric, since it will vary with the number of fish caught. As you can see, deployment time varied a lot within years. You'll also notice that there are a bunch where the deployTime is negative, which shouldn't be happening. I'm going to open a new GH issue to look into this: I don't know what's going on.

_Originally posted by @kaijagahm in https://github.com/MFEh2o/db/issues/50#issuecomment-658888365_

**Comment by kaijagahm** [comment]
It seems like these mistakes are due to some excel dragdown errors. Here's a new version of the above text file, this time showing all the columns. Take a look at dateTimeSet: we have sequential dates, and then July 20th is repeated over and over.

I am guessing that the dateSet for all of these should be 7/03, which is what's shown in the dateSet column--fixing this would then be as simple as changing the date portion of dateTimeSet to 7/03. But given that there are errors in dateTimeSet, I think we should check the original data sheets to make sure the other date/time columns are indeed correct.

@joneslabND can you add this to your list of "physical data sheets to check"?
Or, if the minnow trap sheets are the ones that are in a box at Cary, then maybe @ctsolomon will need to look sometime later when the move has been completed.
[MT_deploy_times.txt](https://github.com/MFEh2o/db/files/5016508/MT_deploy_times.txt)

**Comment by joneslabND** [comment]
These should be here in South Bend.

**Comment by joneslabND** [comment]
These definitely look like drag down errors. The Dates for dateTimeSet are weeks after dateTimeSample and they differ from the dateSet. In these specific examples (MT_deply_times.txt), I think we could use the effort hours and dateTimeSample to recreate the dateTimeSet. In general, hopefully most of these timing errors only have an error in dateTimeSet or dateTimeSample (and not both) and we can use the effort column to fix the problems?

**Comment by kaijagahm** [comment]
Okay, thanks @joneslabND. I'll look into using the effort hours to recreate these, and we'll see if that turns up anything weird.

**Comment by kaijagahm** [comment]
Update on this. So @joneslabND is right that we can use the "effort" value to double check. But that doesn't resolve the disagreement between dateSet and dateTimeSet, or dateSample and dateTimeSample. These do indeed look like dragdowns, and the dateSample portion of the sampleID agrees with the date in dateSample, rather than the date in dateTimeSample, so I've gone ahead and replaced the date portion of dateTimeSample with the date from dateSample, and the date portion of dateTimeSet with the date from dateSet. Then I checked to make sure the difference between those times matched the values in "effort", and they did. Problem solved.

However, I've now turned up a new problem. Decided it would be a good idea to check for any other rows in FISH_SAMPLES where the date in dateTimeSet != the date in dateSet, or where the date in dateTimeSample != the date in dateSample, or (heaven forbid) both.

Unfortunately, there are instances of all three of these types of disagreements. They are NOT the same rows as the negative deploy time rows fixed above; I think that part of the problem is resolved.

I'm attaching the most problematic rows, those with mismatches for both dateSample AND dateSet, here. Luckily, that's only 13 rows. I don't know where to start with fixing these, since there is date/time information in several places and I'm not sure what's correct.

Some observations about this file:
1. For all but a couple rows, the "effort" value matches the difference between dateTimeSample and dateTimeSet.
2. The time (hhmm) portion of the sampleID string matches the time portion of dateTimeSample
3. The date (yymmdd) portion of the sampleID string does NOT match the date portion of dateTimeSample
4. dateSet does not match the date portion of dateTimeSet
5. dateSample does not match the date portion of dateTimeSample.

Anyone have thoughts on how to resolve this? Do we need to go back to the datasheets for these rows? @ctsolomon @joneslabND @Randinotte 

For what it's worth, preventing this type of problem is one of the benefits of "normalizing" database table structure to minimize duplication of information in multiple columns in the same table. Whether this is a big enough problem to e.g. remove the (redundant) dateSet and dateSample columns entirely is a philosophy question--thus far, we've sided with keeping them to facilitate data analysis. But depending on how worried we are about this finding, might be worth considering removing the columns.

**Comment by kaijagahm** [comment]
Here are additional text files for the rows where dateSet doesn't match dateTimeSet (but dateSample and dateTimeSample match), and for the rows where dateSample doesn't match dateTimeSample (but dateSet and dateTimeSet match).

I looked through these for patterns and couldn't find clear ones, or at least, any patterns aren't consistent throughout the table. May be best to ground-truth with data sheets, or to go over this in more detail at a meeting.
[date_groundtruthing_dateSetMismatch.txt](https://github.com/MFEh2o/db/files/5137030/date_groundtruthing_dateSetMismatch.txt)
[date_groundtruthing_dateSampleMismatch.txt](https://github.com/MFEh2o/db/files/5137031/date_groundtruthing_dateSampleMismatch.txt)

**Comment by kaijagahm** [comment]
@joneslabND @ctsolomon @Randinotte just wanted to follow up on our discussion of minnow traps from earlier today, just to note that I had forgotten--the inclusion of non-minnow-trap rows in the text files above was deliberate. I fixed the minnow trap issue according to Stuart's idea about using the effort column, and then I decided to check the rest of the rows in FISH_SAMPLES for good measure. The errors that I found when I did that include both some minnow trap samples (different ones than the ones that had negative deploy times--those did get fixed!) and some regular fish samples.

Still putting this issue on the back burner until Randi's free to help with it, but just wanted to resolve that point of confusion. Sorry for not coming more prepared.

**Comment by Randinotte** [comment]
Went through fish datasheets tonight and found the great majority of datasheets. Color coded by problem type in sheets below.

[date_groundtruthing.xlsx](https://github.com/MFEh2o/db/files/5586496/date_groundtruthing.xlsx)
[date_groundtruthing_dateSampleMismatch.xlsx](https://github.com/MFEh2o/db/files/5586497/date_groundtruthing_dateSampleMismatch.xlsx)
[date_groundtruthing_dateSetMismatch.xlsx](https://github.com/MFEh2o/db/files/5586498/date_groundtruthing_dateSetMismatch.xlsx)

**Comment by kaijagahm** [comment]
@ctsolomon You had asked me to send along these excel sheets so you could look for the gonad survey data sheets (which Randi couldn't find--you said they're at your house).

Rather than email these to you, I'm just tagging you here. In the above three spreadsheets, Randi has color-coded the rows. The *orange* rows are the gonad survey rows.

Let me know if you're confused about any of this or need more info.

Thanks!

**Comment by ctsolomon** [comment]
@kaijagahm I filled in info in the orange rows wherever I could - see the updated versions of those three spreadsheets, which I am uploading here. There's a "CTS comments" column that tries to narrow in on possibilities for rows where I couldn't immediately find the right data sheet. Happy to dig back in if you need me to.
[date_groundtruthing_dateSampleMismatch.xlsx](https://github.com/MFEh2o/db/files/5623903/date_groundtruthing_dateSampleMismatch.xlsx)
[date_groundtruthing_dateSetMismatch.xlsx](https://github.com/MFEh2o/db/files/5623904/date_groundtruthing_dateSetMismatch.xlsx)
[date_groundtruthing.xlsx](https://github.com/MFEh2o/db/files/5623905/date_groundtruthing.xlsx)

**Comment by kaijagahm** [comment]
Began working through Chris's edits. Did most of the dateSample mismatch, except for the one for which he couldn't find a definitive data sheet match. Come back to this.

**Comment by kaijagahm** [comment]
Fixed two of the three that Chris couldn't find. Still waiting to hear back about the tally marks for the third one (the 6-page data sheet). Added a whole bunch of rows for that one. Based on best guesses, also fixed the two that Randi couldn't find.

Will need to do more checks on the times now, and then run through issue 51. Also finish up the tally mark issue.

**Comment by kaijagahm** [comment]
@ctsolomon at the meeting, you asked me to check whether the gonad survey metadata reflected the fact that some fish were tallied without being measured. I checked, and it doesn't. I'm going to make a quick note in the metadata document about this, which I'll flesh out once we've checked more comprehensively through the data sheets and determined the extent of the tally marks.

**Comment by kaijagahm** [comment]
Next steps on this issue:
- Decide whether to deal with the tally marks here, or deal with them wholesale when we check the data sheets.
- Do a final check through FISH_SAMPLES to make sure that the times and dates all match up, and that there are no negative times left.
- After this, can close this issue and turn our attention to #51.

**Comment by kaijagahm** [comment]
I've made pretty good progress on this issue (see to-do list in the comment above). Currently working on doing a last check through the samples to make sure everything is resolved.

I've run across a few more time discrepancy issues (this time between the sampleID and the dateTimeSample, which I guess I forgot to check last time) that I'll need to check data sheets on. They are:

- KT_FN3_20170628_1015_FN_GonadSurvey.20170915 (sampleID says 1015, but dateTimeSample and effort columns suggest that it's actually 1035.)

**Comment by ctsolomon** [comment]
Re query in previous post on KT_FN3_20170628_1015_FN_GonadSurvey.20170915: On the data sheet the dateTimeSample is recorded as 2017-06-28 1015.

**Comment by kaijagahm** [comment]
Next steps on this issue:
- Can't finalize until I've resolved the missing updateID's issue--will talk about that with Randi on Monday.
- ~Add a comment to the mis-numbered fishID's in KT_FN3_20160602_0910_FN_GonadSurvey.20160623.~
- ~Decide whether to deal with the tally marks here, or deal with them wholesale when we check the data sheets.~ (EDIT: decided on a separate issue: #109.)
- ~Do a final check through FISH_SAMPLES to make sure that the times and dates all match up, and that there are no negative times left.~
- Cross-check the sampleID's with any other database tables, for cases when the sampleID changed. [NEXT]
- After this, can close this issue and turn our attention to #51.

**Comment by kaijagahm** [comment]
@Randinotte a few more data sheet checks that I missed the first time around (and have now caught, thanks to the nifty new check functions!)

There's no mystery here--I know exactly what's going on. All of the rows in this text file rolled over midnight, but the date is still the same for set and sample. So I just need to know which date is the correct one (i.e. do I change dateSample, dateTimeSample, and the sampleID, or do I change dateSet and dateTimeSet?)

I'm guessing all the ones from the same lakes will follow the same pattern, so hopefully this will be pretty quick.

Thank you!
[midnightRollovers.txt](https://github.com/MFEh2o/db/files/5784189/midnightRollovers.txt)

**Comment by kaijagahm** [comment]
Also found a bunch of rows with the same dateTimeSet and dateTimeSample. Emailed Chris, Stuart, Randi about whether and how to dig into that.

**Comment by kaijagahm** [comment]
Opted to dig into it: Randi will take a look at some data sheets. 
@Randinotte here are the 52 rows with the same dateTimeSample and dateTimeSet that have actual non-00:00:00 times.

[sameTime.txt](https://github.com/MFEh2o/db/files/5788528/sameTime.txt)

**Comment by Randinotte** [comment]
A question while I'm working- In the midnightRollovers.txt the updateID is "NA". Is that because it's in process, or should we have values there?

Here is a .txt file of the checked dates with comments. Some of the older ones just don't seem to have good dates recorded, so that's probably why they have "00:00" as times. Others were human errors writing the wrong date after the midnight mark. 

[midnightRollover_datasheets.pdf](https://github.com/MFEh2o/db/files/5788765/midnightRollover_datasheets.pdf)
[midnightRollovers_checked.txt](https://github.com/MFEh2o/db/files/5788766/midnightRollovers_checked.txt)

**Comment by kaijagahm** [comment]
Thanks, Randi!

Good question about the NA's. I think it's an error in the script somewhere (because I checked, and I definitely do have the latest version of the database downloaded). I had noticed this when I wrote out the file for you, so it's on my list of things to dig into. Thanks for pointing it out.

**Comment by kaijagahm** [comment]
Stalled in final checks because of 00:00/midnight errors, discovered with the new `sameTime()` check function. Will discuss tomorrow in meeting and decide how to proceed.

**Comment by Randinotte** [comment]
> Opted to dig into it: Randi will take a look at some data sheets.
> @Randinotte here are the 52 rows with the same dateTimeSample and dateTimeSet that have actual non-00:00:00 times.
> 
> [sameTime.txt](https://github.com/MFEh2o/db/files/5788528/sameTime.txt)

RE: these samples that had the same dateTimeSet and dateTimeSample, here's a generalized break down and the annotated check .txt file. 

(Groups correspond to column commentGroup in .txt file)

Group 1 (n=11): Long Lake MarkRecap.20120228 samples (AN and BE) where the db has only the dateTimeSet but the datasheet has both. Typically in Randi_comments as "on datasheet, matches math" meaning that the correct_dateTimeSample is what I found on the datasheet and the time difference and number of crew members correctly calculates the effort listed on both the datahseet and the db. Not sure why this happened, chalking it up to "2012 was early on and it's an easy mistake." For fix: dateTimeSample and sampleID changes (in FISH_SAMPLES and FISH_INFO)

Group 2 (n=3): based on Group 1. Same metadataID/project but dateTimeSet was blank. Using the math from the angler hours and crew, it would make sense that dateTimeSet would be two hours earlier for each of these three. For fix: dateTimeSet could be added based on math.

Group 3 (n=18): Missing datasheets
. Can't find datasheets from September 2012. Likely from Fall Trip and not placed in the datasheet binder. Can check other binders but not likely. They're from the same MarkRecap.20120228 as Group 1-2, so it's likely that the effort could be used to calculate the correct times, but we wouldn't know for sure. For fix: I recommend no change because we don't have the sheets.

Group 4 (n=4): Gonad survey, don't have datasheets. For fix: I recommend no change because we don't have the sheets. 

Group 5 (n= 14): Seine nets, no times changed in either column. Same set/sample time OK for DietSurvey.20120624. For fix: no changes needed

Group 6 (n= 2): Misc. See comments. For fix: use correct_dateTimeSet and correct_dateTimeSample

[sameTime.txt](https://github.com/MFEh2o/db/files/5803165/sameTime.txt)

**Comment by kaijagahm** [comment]
> In the midnightRollovers.txt the updateID is "NA". Is that because it's in process, or should we have values there?

@Randinotte Thanks again for catching this. It was--you guessed it!--a rogue case_when() statement in my own code. UGH.

**Comment by Randinotte** [comment]
@kaijagahm is there conceivably a check function that would read through the script and check for unfinished case_when()'s?

**Comment by kaijagahm** [comment]
Closed with v 4.3.0

**Comment by kaijagahm** [comment]
Here is a notes document that I used for this issue. I don't think it'll be needed, since the issue has been resolved, but just in case: 
[FSMismatchedTimesMoreDetails.docx](https://github.com/MFEh2o/db/files/6870580/FSMismatchedTimesMoreDetails.docx)
