### ISSUE TITLE
Remaining METADATA issues

### ISSUE THREAD

**Issue by kaijagahm** [MFEh2o/db#71]
There's still some confusion about the metadata file that Patrick sent (ZoopCounts) in relation to the already-existing ZoopCounts files and descriptions. Waiting to hear back from him with clarifying details.

Still waiting on Stuart to check some files for the MT deploy times issue. See #60 .

_Originally posted by @kaijagahm in https://github.com/MFEh2o/db/issues/50#issuecomment-674055450_

**Comment by kaijagahm** [comment]
@Randinotte the above (going over the ZoopCounts metadata file that Patrick sent me in relation to the files that are already there) is one thing I want to go over with you tomorrow. MT deploy times are another.

**Comment by kaijagahm** [comment]
Issue stalled because we can't figure out what's going on with the different ZoopCounts metadata docs. Described this more in my notes after my meeting with Randi: 

![image](https://user-images.githubusercontent.com/37053323/94598715-5965f400-025d-11eb-8fe3-fe1d2836dacd.png)

**Comment by kaijagahm** [comment]
Described this issue fully in a 10/16 email to CTS, SEJ, RN. Followed up on that email chain today (12/9).

**Comment by Randinotte** [comment]
Noticed while looking into the ZoopCounts.2011MMDD metadata issue... 

The metadataID string in a sampleID should reflect the sample's collection protocol. Then, the metadataID column in the table should reflect the way the sample was analyzed. The two should only match if the same document covers the sample's collection and analysis, and I suspect that's not usually the case. Many rows in ZOOPS_LENGTHS, ZOOPS_SUBSAMPLE, and ZOOPS_ABUND_BIOMASS have matching metadataIDs in their sampleIDs and column metadataID. 

Noting this here so that I can come back to the problem when I can give it a lot of attention.

**Comment by kaijagahm** [comment]
Notes from 12/15 meeting:

o	Are there duplicate zoopcounts for samples in 2011? Undergrads may have counted some 2011 samples, and then Patrick re-counted them.  (lake/date combinations; sampleID’s might differ in their metadataIDs).
o	Want to collapse the 2011 metadatas into a single one, which we can call June 1st. Make one most complete version of the metadata. 
o	Zoop counts and biomass data should be consistent from 2011-2014—should use same metadata. Exception would be whether there are duplicate counts for 2011. 
o	Next time there should be any change in zooplankton metadata is when Alex showed up—2015 or 2016. There was a difference there—should have new metadataID. 
o	Is there length data with one metadataID and count data with the other metadataID from the same lake on the same date—that would be the same sample. Might have two different metadataID’s.

**Comment by kaijagahm** [comment]
I checked 2011 and sure enough, we do have some duplicate samples--same date, lake, depthclass, and site, but different metadata. Looks like Stuart is right that these zoops were measured twice: once by the undergrads and then once by patrick for consistency.

In the meeting, Stuart mentioned that we want to condense these metadatas down into a single document for 2011. I guess the question then is going to be how to differentiate these measurements from the undergrads vs. Patrick. i.e. should we just remove the undergrads' measurements? Or be okay with having duplicates? Presumably we should put a note about this duality into the metadata doc itself.

**Comment by kaijagahm** [comment]
We checked the other ZOOPS* tables, and it looks like the only one where the 5/17 metadataID appears is ZOOPS_LENGTHS. This is weird, because it looks like if the undergrads measured the same zoops with a different protocol, there's no record of them having subsampled.

We're basically ready to remove those duplicate samples from the database, since there's no attached protocol or subsample information (making the lengths useless for calculating biomass anyway). Going to just confirm that with Stuart and Chris at the 1/5 meeting.

**Comment by kaijagahm** [comment]
Removed duplicate samples from the database in the gh71 script. The version of the metadata protocol on Box is already the most recent one.

**Comment by kaijagahm** [comment]
Closed with v 4.3.0
