### ISSUE TITLE
FISH_SAMPLES FISH_INFO late summer 2019 fish data missing

### ISSUE THREAD

**Issue by kaijagahm** [MFEh2o/db#79]
Not all fish data from 2019 made it into the database--some missing samples from late July and August. Colin sent me some csv's via Slack that should be the complete versions of FISH_SAMPLES and FISH_INFO, including the new samples. (I can't attach them here because they're csv's, bleh). 

Going to table this until Randi has time to look at it, so I can make sure to add the samples correctly.

**Comment by Randinotte** [comment]
Commenting here regarding the missing Fall Trip fish noticed by @ctsolomon today. 

To find the fall trip fish I looked at which csv's I had available when I did the update. In Summer 2019 (OneDrive Archive on Box) there are individual sampling event csv's and what I thought were completely compiled fishInfoIS csv's. The compiled fishInfoIS_BE-AN.csv HAS the 2019 Fall Trip samples. I need to look into the script I used to make the 2019 fish update and see why these samples got left out. Hopefully that will shed light on the missing samples that Colin noticed.

**Comment by Randinotte** [comment]
Update RE: missing Long fish samples, it looks like a date formatting error caused all angling and shocking data to not rbind to the full fishSamplesIS dataframe that I was working with. Fixing those dates will resolve the missing samples that Chris was looking for. 

RE: Colin's missing samples, I compared his csv's for fishSamplesIS and fishInfoIS and found that they are not the same copies that I had at the end of March when I made the update. I should have realized that my copy was incomplete. The same is true for fishInfoIS in FISH_INFO.

To resolve both problems of missing data I'm going to recreate that fish update "sampleFishInfo2019.20200529" for both FISH_SAMPLES and FISH_INFO.

**Comment by ctsolomon** [comment]
OK, thanks. Can you coordinate with @kaijagahm to make sure that recreating that update doesn't create any problems given the other updates she has made in the meantime? If easier we could just do a new update that adds only the missing samples/fish.

**Comment by Randinotte** [comment]
@ctsolomon Yes, I tagged her in a slack asking what process would work best based on how soon she planned to update.

**Comment by kaijagahm** [comment]
Hi @Randinotte: so I actually just made a db update, before checking Slack. I'm sorry! But this shouldn't be a big problem, I'll just do another mini-update pretty soon (3.5.1, not 3.6.0). 

It would be best if you could send me just the _new_ rows in FISH_SAMPLES, _not_ the entire FISH_SAMPLES table. I haven't made any changes to FISH_SAMPLES, so it shouldn't be a problem to add on those rows.

What is your timeline for getting the new rows to me? Are we talking tonight, or a week from now, or a month? Doesn't matter to me, just getting a sense of it.

**Comment by Randinotte** [comment]
@kaijagahm You're too good! Yeah, putting it in as a small update is no problem. I think I'll have it done by the end of the week (Friday night). 

Ok, I'll just send FISH_INFO and FISH_SAMPLES rows that weren't included in sampleFishInfo2019.20200529.

**Comment by kaijagahm** [comment]
Wait, I'm confused--I thought you said in slack that the rows were already in FISH_INFO, but not in FISH_SAMPLES?

Either way, it doesn't matter. Send me the new rows and I'll add them :).

**Comment by kaijagahm** [comment]
@Randinotte just to check in on this issue--are these data the ones that you're adding to the current database update that you're working on now?

**Comment by Randinotte** [comment]
@kaijagahm Yes, this issue will be resolved with my upcoming update! I figured out how each set got left out and will document when it's finished.

**Comment by kaijagahm** [comment]
Finished in Randi's 20201215 update, "Second Wave"
