### ISSUE TITLE
LAKES update lat/long and add source

### ISSUE THREAD

**Issue by kaijagahm** [MFEh2o/db#84]
1. Update lat/long of lakes that Eva was able to find using the app.
2. Add a note for the other lakes about the lat/long source
3. Add lat/long for the lakes she wasn't able to find.

**Comment by kaijagahm** [comment]
Need to check back in with Stuart about the surface area question. Leaving that as is for now.

**Comment by kaijagahm** [comment]
Updated lat/long from Eva's spreadsheet, and also added a few from Google maps when I could find them. Added a new latLongSource column. Removed a row for a lake that was in two different counties. Created the meta_3.5.1 script and made the entry for this issue.

**Comment by kaijagahm** [comment]
@Randinotte as we discussed at the meeting, can you take a look at the remaining lakes, some of which are UNDERC lakes, and see if any of them are familiar to you? If they are, go to Google Maps, click on the center of the lake, and grab its lat/long coords and fill them in. If there's a lake listed that you don't know, don't try to find it--I've already Googled extensively and done pretty much all the sleuthing there is to be done absent prior knowledge. You can just leave any unfamiliar ones blank.

The file is [here](https://docs.google.com/spreadsheets/d/1ADX4EnDCK2PFcji9IYqFCzpcU_PanfMbqpFPd4tb5XQ/edit#gid=541245300). Go to the second sheet, labeled "forRandi". 

Thanks!

**Comment by Randinotte** [comment]
I don't think this needs immediate attention but thought it could provide insight if there's ever any more work done on the app to improve the search success... 

While working on the CREEL updates I encountered a new lake that's not in the database. "Aha! The perfect example case for Kaija's app!" It's called Landing Lake and is fully in Vilas County, WI. On Google Maps it is labeled "Landing Lake" and is surrounded by other labeled lakes. However, the app doesn't have a listing for Landing Lake. (Search Black Oak Lake in Vilas and look just to the east for Landing). Looking closer (literally), Google Maps has the lake labeled as "Landing Lake" for the western basin and "Mill Lake" for the eastern basin, but only "Mill Lake" appears until you zoom in further. Once you're zoomed in far enough, GM has both labels. Alternatively, the app shows the whole lake as "Landing Lake" and when you zoom in it shows "Mill Creek" inside the lake. 

![image](https://user-images.githubusercontent.com/49883663/95257469-5ab19680-07f2-11eb-8c71-c0adc8703722.png)
![image](https://user-images.githubusercontent.com/49883663/95257525-71f08400-07f2-11eb-8c25-ea95dcbf4129.png)

**Comment by kaijagahm** [comment]
Yeah, so, this is a known limitation of the app. As it's currently written, it overlays shapefiles onto a map base layer. So when you click on the lake polygons, you're not actually interacting at all with the base map layer, just with the overlaid polygons.

The reason for the discrepancy between labels in GM vs the base map of the app is that the base map isn't literally a google map--it's one of many base map choices that are provided in Leaflet. So yeah, they probably have different priorities for which labels to display when, or something.

I don't know of a way to get Landing Lake to actually show up meaningfully in the app (i.e. to be clickable) except by joining and adding other lakes shapefiles. That would be a question for @joneslabND, who pointed me to the shapefiles that we're currently using for the app. If I were to find other shapefiles that would include more lakes, we'd have to make sure they were authoritative and resolve any conflicts with the exisiting shapefiles (i.e. if different shapefiles have the polygon borders drawn *slightly* differently...)

**Comment by kaijagahm** [comment]
Randi filled in most of the UNDERC lakes (and also with a bit of help from Colin). I incorporated these changes, changed the latLongSource to "unknown" when necessary, and made a couple other changes (added comment to EV; changed lakeName (but NOT lakeID!) for Twin --> South Twin (TW)). All edits made in script LAKES_latlong_gh84.R

Ready to write files and run meta script.

**Comment by Randinotte** [comment]
@kaijagahm When I made the creel update database I added a lake (Landing "LD"). I wanted to bring that to your attention in case that new lake won't come up in your updating process when you make this update to LAKES.

**Comment by kaijagahm** [comment]
Thanks! I will keep an eye out for it. What did you do about its lat/long?

**Comment by Randinotte** [comment]
Landing wasn't in the lake finder app so I selected the approximate center from Google Maps

**Comment by kaijagahm** [comment]
Ok, I noted this in the new latLongSource column.

Ready for db update on this script.

**Comment by kaijagahm** [comment]
Fixed with v 3.5.2, 2020-10-20
