### ISSUE TITLE
SITES inconsistencies

### ISSUE THREAD

**Issue by Randinotte** [MFEh2o/db#86]
Some sites are listed as lakeID_WholeShoreline and others as lakeID_wholeShoreline. Fixing that should be simple, but the thread pulls out all the other tables where the capital "W" wholeShoreline site names exist in siteID's, sampleID's, boatID's, trailerID's, and fishID's. 

The original creel tables had "WholeShoreline" so that's what I used, but when it came time to check that every site was in SITES before the update, I learned of this error. In the interest of getting the CREEL update to Ashley ASAP, I left all the creel tables as "WholeShoreline" even though many (n=21) are capital W in the CREEL tables and lowercase w in SITES.  (updateID creelUpdates_20201007)

**Comment by Randinotte** [comment]
Additionally, it seems standard practice for lat/long's to be copied from LAKES for new sites at existing lakes. However, it doesn't make sense to put the same set of lat/longs for the DeepHole, WholeShoreline, and BoatLaunch. (Unless these are just supposed to be rough so they can be plotted quickly?)

**Comment by ctsolomon** [comment]
I would say that any lat/long in the SITES table should be specific to the site - not just a copy of the lat/long that we use for the lake. Going forward, this means that people should either document the lat/long of a site or else leave those fields NA when they create a new site.

**Comment by joneslabND** [comment]
Agreed!

**Comment by kaijagahm** [comment]
The wholeShoreline/WholeShoreline issue got resolved along with the other sampleID edits in e.g. #51 . 

I'm going to close this issue and make a new one for adding lat/long to the existing sites.
