### ISSUE TITLE
Duplicated invertID's in BENTHIC_INVERTS (and photo/database discrepancies)

### ISSUE THREAD

**Issue by kaijagahm** [MFEh2o/db#88]
Here's an example of the problem, which I sent to Alex today. See also screenshots in the Slack "database" channel, and the CSV that I can't attach here because Github makes this unnecessarily difficult. See 2018BugLengthCheck2020_gh33 (from #33) for more details and the code to get these examples.
[MysteryBugs - Page 1.pdf](https://github.com/MFEh2o/db/files/5410371/MysteryBugs.-.Page.1.pdf)

**Comment by kaijagahm** [comment]
Chatted with Chris about this on 10/23 morning. We couldn't figure out the issue after sorting by tray number and examining individual sampleID's. Next step is for Chris to investigate one or two of the problematic sampleID's by going into the photo archive and taking it bug by bug. I've sent him csv's of the data for three out of the ten problematic sampleID's, along with the rows for all bugs in the trays corresponding to those sampleID's. Sent via email 10/23.

**Comment by kaijagahm** [comment]
Update: Chris checked on three of the sampleID's, and I was able to follow up on that and figure out which bugs were intended (bugs from the same date). 

As of today or yesterday, Chris has now gone through most of the rest of the sampleID's, so this is back in my court.

**Comment by kaijagahm** [comment]
Forgot to update this--as of a few days ago, I've gone through Chris's responses and suggested actions for each of them.

For the remaining ones that are still unclear, I'm going to bring it up at the next meeting.

**Comment by kaijagahm** [comment]
Chris went over my notes and responded.

We have two documents: "duplicate invertID in BENTHIC_INVERTS.docx" (first three sampleID's), and "duplicate invertID in BENTHIC_INVERTS - take 2 - CTS.docx" (last seven sampleID's)

As of 11 December 2020 evening, I've gone through and fixed all the problems in the first document, except for the following:
FE_S_3 on 2018-06-25 has 0 rows in the database, but there's a photo with three bugs. Have Amaryllis add these.
FE_NW_3 on 2018-06-25 (same date) has 0 rows in the database, but photos show 19 bugs. Have Amaryllis add these.

Now on to the second document. I'll resolve what I can.

**Comment by kaijagahm** [comment]
To facilitate any photo/database comparisons that we decide to rope Amaryllis into, I'm now going to go back to the database and pull out info on how many bugs we have for each sampleID, sorted by date. I'll put those all into an excel file.

**Comment by kaijagahm** [comment]
@ctsolomon @aadey1 I misremembered--the bug counts spreadsheet that I put together was already here, not in an email. See just above (previous comment).

Amaryllis, I'm assuming you know how to access the BENTHIC_INVERTS photo archive in Box; let me know if you have trouble finding or navigating that.

Unfortunately, I didn't save my raw number comparisons between the bugs from the database vs the photos, but I did save more detailed written notes where I flagged the "problems" (i.e. sampleID's that were off by more than one or two bugs) as part of the issue I was working on with Chris. I'm confident that I pulled out all the problems for the dates that I checked, so you can go ahead and skip the following dates:

2016-05-24
2017-05-10
2017-06-05
2018-05-14
2018-06-11
2018-06-25
2018-07-23
2018-08-06

And one final clarification: why are we checking one date at a time? Two reasons: 1) that's how the photos are organized, so it's easier, and 2) Chris had the bright idea that most mistakes and sampleID swaps/typos would probably have occurred between sampleID's from the same date, because of the way the data were entered. Sure enough, when we started sorting through errors, that very often turned out to be the case.

That said, of course, Chris and I did find a few mysteries that we couldn't clear up, so we might end up needing some cross-date comparison at some point. That's where having all these dates checked will come in handy.

Feel free to reach out if you have any questions!

**Comment by aadey1** [comment]
Thank you, Kaija!

I really appreciate your help/guidance with this! I think that makes sense
for why to do each individually and by date. I have accessed the bug photos
in the past, but will let you know if I forget where they are (an all too
likely possibility haha).

I will let you and Chris know if I encounter any issues.

Thanks again, and see you next week via zoom!
Amaryllis

**Comment by kaijagahm** [comment]
@aadey1 @ctsolomon I checked through the dates listed above. Here's the breakdown of "no problems (i.e. not off by more than one or two bugs" vs. "still problem(s) remaining"

2016-05-24: no problems
2017-05-10: problem remaining
2017-06-05: problem remaining
2018-05-14: no problems
2018-06-11: problem remaining
2018-06-25: problem remaining
2018-07-23: problem remaining
2018-08-06: no problems

I hope that helps!

**Comment by kaijagahm** [comment]
Next to do: pull together "a summary by year of what proportion of samples were checked and what proportion had problems" (-CTS)

**Comment by joneslabND** [comment]
A couple ideas for avoiding these issues with data entry moving forward. Would be good to capture these in metadata or protocols moving forward...
*put label from vial in photo
*script for updating bug files could check for all samples (have to deal with NFK for bugs)
*keep doing photo number recording in in-season counting sheet

**Comment by kaijagahm** [comment]
Updates:
- Amaryllis finished checking the bugs. She noted when there were large discrepancies between the database and photo counts, when there were missing photos, when bugs in photos were missing from the database, when bugs were mis-labeled, etc.
- She sent me the attached excel file (I'm attaching the most recent version, with a few of my edits, as of the afternoon of 12 Feb 2020)
[amaryllisSummary.20210211.KGedit.xlsx](https://github.com/MFEh2o/db/files/5973953/amaryllisSummary.20210211.KGedit.xlsx)
- I have just started to go through the PendingIssues sheet. So far, I have gone through the gray section. I created a csv file called "bugsToAddTemplate.csv" (sent via slack on 2021-02-12) containing blank rows for Amaryllis to fill in.
- Noted that we have a bunch of rows already in BENTHIC_INVERTS that have missing invertNums and therefore missing/incomplete invertID's. These come from Alex's bugFix in 2018, and from my taxonomy update in 2020.
- The taxonomy update updateID never got entered into UPDATE_METADATA, along with another updateID: they were supposed to be entered in meta_3.5.3, but I forgot to bind the new rows to the table. Oops. Will need to use the next meta script to add these in.
- Need to trace back the missing invertNums in my script, and then possibly also in Alex's script. Yuck.
- Once Amaryllis fills in her rows, I will have to figure out how to number the new bugs, especially the ones that are going on top of already-existing sampleID's. Since these are in the minority, manual may be the way to go. For the ones where no bugs from that sampleID were included, I can simply number them in order.

Next steps, while waiting for Amaryllis to send in those rows:
- For sampleID's with missing photos, make a note in BENTHIC_INVERT_SAMPLES comments, to avoid clogging up the comments in BENTHIC_INVERTS.
- Deal with the non-gray rows in the spreadsheet: edits, fixes, etc. If sampleID's are changed, be sure to trace them through to other tables in the database.

**Comment by kaijagahm** [comment]
- Made notes in BENTHIC_INVERT_SAMPLES for the ones that were missing photos.
- Made most fixes. Waiting to hear back from Chris on one of them, and need to meet with Randi about a few others.
- Will incorporate Amaryllis's new rows.
- Have fixed the invertNum issue.
- Need to close out this BENTHIC_INVERTS issue before moving on to resolving sampleID's in #51

**Comment by kaijagahm** [comment]
Resolved with database update 4.5.0.
