### ISSUE TITLE
sampleID time format

### ISSUE THREAD

**Issue by Randinotte** [MFEh2o/db#97]
Just learned that some sampleID's have 3-digit times (eg. 952) instead of 4-digit times (eg. 0952) in their sampleIDs. They all happened in early 2020 when I hadn't known that the 4-digit time format was standard. It's not crucial that they get changed, but it's just an inconsistency. In SAMPLES, 582 sampleIDs have 3-digit times and fall in the updateID's: sampleChlorophyll.20200203, sampleGC.20200331, sampleStaff.20200331, sampleColor.20200203, and sampleDOC.20200203. SampleIDs would have to be changed in all of their tables: CHLOROPHYLL, GC, STAFF_GAUGES, COLOR, and WATER_CHEM. This doesn't occur in FISH_SAMPLES.

**Comment by kaijagahm** [comment]
I recall seeing this while working on #51. That issue should fix it. If not, we'll circle back to this.

**Comment by kaijagahm** [comment]
Should be fixed with update 4.5.0.
